// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debrid.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteDebridAccountByProvider = `-- name: DeleteDebridAccountByProvider :exec
DELETE FROM debrid_accounts WHERE provider = $1
`

func (q *Queries) DeleteDebridAccountByProvider(ctx context.Context, provider string) error {
	_, err := q.db.Exec(ctx, deleteDebridAccountByProvider, provider)
	return err
}

const listDebridAccounts = `-- name: ListDebridAccounts :many
SELECT id, provider, api_key_enc, enabled, priority
FROM debrid_accounts
ORDER BY priority DESC, provider
`

type ListDebridAccountsRow struct {
	ID        uuid.UUID
	Provider  string
	ApiKeyEnc []byte
	Enabled   bool
	Priority  int32
}

func (q *Queries) ListDebridAccounts(ctx context.Context) ([]ListDebridAccountsRow, error) {
	rows, err := q.db.Query(ctx, listDebridAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDebridAccountsRow{}
	for rows.Next() {
		var i ListDebridAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ApiKeyEnc,
			&i.Enabled,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDebridAccount = `-- name: UpsertDebridAccount :exec
INSERT INTO debrid_accounts (provider, api_key_enc)
VALUES ($1, $2)
ON CONFLICT (provider) DO UPDATE
SET api_key_enc = EXCLUDED.api_key_enc,
    enabled     = true,
    updated_at  = now()
`

type UpsertDebridAccountParams struct {
	Provider  string
	ApiKeyEnc []byte
}

// Config bootstrap (P3.1): one account per provider. The key is sealed by
// internal/secret before it gets here; a changed key re-seals on the next
// start, and enabling again is implicit.
func (q *Queries) UpsertDebridAccount(ctx context.Context, arg UpsertDebridAccountParams) error {
	_, err := q.db.Exec(ctx, upsertDebridAccount, arg.Provider, arg.ApiKeyEnc)
	return err
}
