// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: displayprefs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getDisplayPreferences = `-- name: GetDisplayPreferences :one

SELECT data FROM display_preferences WHERE user_id = $1 AND pref_id = $2 AND client = $3
`

type GetDisplayPreferencesParams struct {
	UserID uuid.UUID
	PrefID string
	Client string
}

// Display preferences per user, key and client (TASKS P1.23).
func (q *Queries) GetDisplayPreferences(ctx context.Context, arg GetDisplayPreferencesParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getDisplayPreferences, arg.UserID, arg.PrefID, arg.Client)
	var data json.RawMessage
	err := row.Scan(&data)
	return data, err
}

const upsertDisplayPreferences = `-- name: UpsertDisplayPreferences :exec
INSERT INTO display_preferences (user_id, pref_id, client, data) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, pref_id, client) DO UPDATE SET data = EXCLUDED.data, updated_at = now()
`

type UpsertDisplayPreferencesParams struct {
	UserID uuid.UUID
	PrefID string
	Client string
	Data   json.RawMessage
}

func (q *Queries) UpsertDisplayPreferences(ctx context.Context, arg UpsertDisplayPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertDisplayPreferences,
		arg.UserID,
		arg.PrefID,
		arg.Client,
		arg.Data,
	)
	return err
}
