// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getImage = `-- name: GetImage :one

SELECT item_id, type, idx, source_url, local_path, tag, blurhash, width, height FROM images WHERE item_id = $1 AND type = $2 AND idx = $3
`

type GetImageParams struct {
	ItemID uuid.UUID
	Type   string
	Idx    int32
}

// Image serving (TASKS P1.17).
func (q *Queries) GetImage(ctx context.Context, arg GetImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, arg.ItemID, arg.Type, arg.Idx)
	var i Image
	err := row.Scan(
		&i.ItemID,
		&i.Type,
		&i.Idx,
		&i.SourceUrl,
		&i.LocalPath,
		&i.Tag,
		&i.Blurhash,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, provider_ids, image_url, updated_at FROM people WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderIds,
		&i.ImageUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const imagesMissingInfo = `-- name: ImagesMissingInfo :many
SELECT im.item_id, im.type, im.idx, im.source_url, im.local_path, im.tag
FROM images im JOIN items i ON i.id = im.item_id
WHERE i.library_id = $1 AND im.blurhash IS NULL
ORDER BY im.item_id, im.type, im.idx LIMIT $2
`

type ImagesMissingInfoParams struct {
	LibraryID uuid.UUID
	RowLimit  int32
}

type ImagesMissingInfoRow struct {
	ItemID    uuid.UUID
	Type      string
	Idx       int32
	SourceUrl *string
	LocalPath *string
	Tag       string
}

func (q *Queries) ImagesMissingInfo(ctx context.Context, arg ImagesMissingInfoParams) ([]ImagesMissingInfoRow, error) {
	rows, err := q.db.Query(ctx, imagesMissingInfo, arg.LibraryID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImagesMissingInfoRow{}
	for rows.Next() {
		var i ImagesMissingInfoRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Type,
			&i.Idx,
			&i.SourceUrl,
			&i.LocalPath,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImageInfo = `-- name: SetImageInfo :exec
UPDATE images SET width = $4, height = $5, blurhash = $6 WHERE item_id = $1 AND type = $2 AND idx = $3
`

type SetImageInfoParams struct {
	ItemID   uuid.UUID
	Type     string
	Idx      int32
	Width    *int32
	Height   *int32
	Blurhash *string
}

// Dimensions and blurhash of the original, filled on first fetch.
func (q *Queries) SetImageInfo(ctx context.Context, arg SetImageInfoParams) error {
	_, err := q.db.Exec(ctx, setImageInfo,
		arg.ItemID,
		arg.Type,
		arg.Idx,
		arg.Width,
		arg.Height,
		arg.Blurhash,
	)
	return err
}
