// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countChildren = `-- name: CountChildren :one
SELECT count(*) FROM items WHERE parent_id = $1
`

func (q *Queries) CountChildren(ctx context.Context, parentID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (library_id, parent_id, top_parent_id, type, name, sort_name,
                   source_kind, path, strm_url, index_number, parent_index_number, production_year)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9,
        $10, $11, $12)
RETURNING id, library_id, parent_id, top_parent_id, type, name, original_title, sort_name, forced_sort_name, index_number, index_number_end, parent_index_number, production_year, premiere_date, end_date, overview, tagline, official_rating, community_rating, critic_rating, runtime_ticks, provider_ids, source_kind, path, strm_url, stremio_ref, etag, date_created, date_modified, date_last_refreshed, is_missing, missing_since, metadata_refreshed_at, metadata_source, original_language
`

type CreateItemParams struct {
	LibraryID         uuid.UUID
	ParentID          *uuid.UUID
	TopParentID       *uuid.UUID
	Type              string
	Name              string
	SortName          string
	SourceKind        string
	Path              *string
	StrmUrl           *string
	IndexNumber       *int32
	ParentIndexNumber *int32
	ProductionYear    *int32
}

// Minimal insert used by tests and the scanner bootstrap; the scanner (P1.14)
// adds a full upsert.
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.LibraryID,
		arg.ParentID,
		arg.TopParentID,
		arg.Type,
		arg.Name,
		arg.SortName,
		arg.SourceKind,
		arg.Path,
		arg.StrmUrl,
		arg.IndexNumber,
		arg.ParentIndexNumber,
		arg.ProductionYear,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ParentID,
		&i.TopParentID,
		&i.Type,
		&i.Name,
		&i.OriginalTitle,
		&i.SortName,
		&i.ForcedSortName,
		&i.IndexNumber,
		&i.IndexNumberEnd,
		&i.ParentIndexNumber,
		&i.ProductionYear,
		&i.PremiereDate,
		&i.EndDate,
		&i.Overview,
		&i.Tagline,
		&i.OfficialRating,
		&i.CommunityRating,
		&i.CriticRating,
		&i.RuntimeTicks,
		&i.ProviderIds,
		&i.SourceKind,
		&i.Path,
		&i.StrmUrl,
		&i.StremioRef,
		&i.Etag,
		&i.DateCreated,
		&i.DateModified,
		&i.DateLastRefreshed,
		&i.IsMissing,
		&i.MissingSince,
		&i.MetadataRefreshedAt,
		&i.MetadataSource,
		&i.OriginalLanguage,
	)
	return i, err
}

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (name, kind, paths)
VALUES ($1, $2, $3)
RETURNING id, name, kind, paths, options, created_at, enabled
`

type CreateLibraryParams struct {
	Name  string
	Kind  string
	Paths []string
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, createLibrary, arg.Name, arg.Kind, arg.Paths)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Paths,
		&i.Options,
		&i.CreatedAt,
		&i.Enabled,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, library_id, parent_id, top_parent_id, type, name, original_title, sort_name, forced_sort_name, index_number, index_number_end, parent_index_number, production_year, premiere_date, end_date, overview, tagline, official_rating, community_rating, critic_rating, runtime_ticks, provider_ids, source_kind, path, strm_url, stremio_ref, etag, date_created, date_modified, date_last_refreshed, is_missing, missing_since, metadata_refreshed_at, metadata_source, original_language FROM items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ParentID,
		&i.TopParentID,
		&i.Type,
		&i.Name,
		&i.OriginalTitle,
		&i.SortName,
		&i.ForcedSortName,
		&i.IndexNumber,
		&i.IndexNumberEnd,
		&i.ParentIndexNumber,
		&i.ProductionYear,
		&i.PremiereDate,
		&i.EndDate,
		&i.Overview,
		&i.Tagline,
		&i.OfficialRating,
		&i.CommunityRating,
		&i.CriticRating,
		&i.RuntimeTicks,
		&i.ProviderIds,
		&i.SourceKind,
		&i.Path,
		&i.StrmUrl,
		&i.StremioRef,
		&i.Etag,
		&i.DateCreated,
		&i.DateModified,
		&i.DateLastRefreshed,
		&i.IsMissing,
		&i.MissingSince,
		&i.MetadataRefreshedAt,
		&i.MetadataSource,
		&i.OriginalLanguage,
	)
	return i, err
}

const listChildren = `-- name: ListChildren :many
SELECT id, library_id, parent_id, top_parent_id, type, name, original_title, sort_name, forced_sort_name, index_number, index_number_end, parent_index_number, production_year, premiere_date, end_date, overview, tagline, official_rating, community_rating, critic_rating, runtime_ticks, provider_ids, source_kind, path, strm_url, stremio_ref, etag, date_created, date_modified, date_last_refreshed, is_missing, missing_since, metadata_refreshed_at, metadata_source, original_language FROM items
WHERE parent_id = $1
ORDER BY coalesce(forced_sort_name, sort_name), id
LIMIT $3 OFFSET $2
`

type ListChildrenParams struct {
	ParentID  *uuid.UUID
	RowOffset int32
	RowLimit  int32
}

// Browse order: forced sort name wins, id breaks ties so paging is stable.
func (q *Queries) ListChildren(ctx context.Context, arg ListChildrenParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listChildren, arg.ParentID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ParentID,
			&i.TopParentID,
			&i.Type,
			&i.Name,
			&i.OriginalTitle,
			&i.SortName,
			&i.ForcedSortName,
			&i.IndexNumber,
			&i.IndexNumberEnd,
			&i.ParentIndexNumber,
			&i.ProductionYear,
			&i.PremiereDate,
			&i.EndDate,
			&i.Overview,
			&i.Tagline,
			&i.OfficialRating,
			&i.CommunityRating,
			&i.CriticRating,
			&i.RuntimeTicks,
			&i.ProviderIds,
			&i.SourceKind,
			&i.Path,
			&i.StrmUrl,
			&i.StremioRef,
			&i.Etag,
			&i.DateCreated,
			&i.DateModified,
			&i.DateLastRefreshed,
			&i.IsMissing,
			&i.MissingSince,
			&i.MetadataRefreshedAt,
			&i.MetadataSource,
			&i.OriginalLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, kind, paths, options, created_at, enabled FROM libraries ORDER BY name
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.Query(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Paths,
			&i.Options,
			&i.CreatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
