// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items_batch.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const childCountsForItems = `-- name: ChildCountsForItems :many
SELECT parent_id::uuid AS item_id, count(*) AS n FROM items
WHERE parent_id = ANY($1::uuid[]) AND missing_since IS NULL GROUP BY parent_id
`

type ChildCountsForItemsRow struct {
	ItemID uuid.UUID
	N      int64
}

func (q *Queries) ChildCountsForItems(ctx context.Context, ids []uuid.UUID) ([]ChildCountsForItemsRow, error) {
	rows, err := q.db.Query(ctx, childCountsForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChildCountsForItemsRow{}
	for rows.Next() {
		var i ChildCountsForItemsRow
		if err := rows.Scan(&i.ItemID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByIDs = `-- name: GetItemsByIDs :many

SELECT id, library_id, parent_id, top_parent_id, type, name, original_title, sort_name, forced_sort_name, index_number, index_number_end, parent_index_number, production_year, premiere_date, end_date, overview, tagline, official_rating, community_rating, critic_rating, runtime_ticks, provider_ids, source_kind, path, strm_url, stremio_ref, etag, date_created, date_modified, date_last_refreshed, is_missing, missing_since, metadata_refreshed_at, metadata_source, original_language FROM items WHERE id = ANY($1::uuid[])
`

// Batch loads for building BaseItemDtos (TASKS P1.19): one query per kind of
// data for a whole page of items.
func (q *Queries) GetItemsByIDs(ctx context.Context, ids []uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ParentID,
			&i.TopParentID,
			&i.Type,
			&i.Name,
			&i.OriginalTitle,
			&i.SortName,
			&i.ForcedSortName,
			&i.IndexNumber,
			&i.IndexNumberEnd,
			&i.ParentIndexNumber,
			&i.ProductionYear,
			&i.PremiereDate,
			&i.EndDate,
			&i.Overview,
			&i.Tagline,
			&i.OfficialRating,
			&i.CommunityRating,
			&i.CriticRating,
			&i.RuntimeTicks,
			&i.ProviderIds,
			&i.SourceKind,
			&i.Path,
			&i.StrmUrl,
			&i.StremioRef,
			&i.Etag,
			&i.DateCreated,
			&i.DateModified,
			&i.DateLastRefreshed,
			&i.IsMissing,
			&i.MissingSince,
			&i.MetadataRefreshedAt,
			&i.MetadataSource,
			&i.OriginalLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersForItems = `-- name: ListChaptersForItems :many
SELECT item_id, idx, start_ticks, name FROM chapters WHERE item_id = ANY($1::uuid[]) ORDER BY item_id, idx
`

func (q *Queries) ListChaptersForItems(ctx context.Context, ids []uuid.UUID) ([]Chapter, error) {
	rows, err := q.db.Query(ctx, listChaptersForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ItemID,
			&i.Idx,
			&i.StartTicks,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenresForItems = `-- name: ListGenresForItems :many
SELECT ig.item_id, g.id, g.name FROM item_genres ig JOIN genres g ON g.id = ig.genre_id
WHERE ig.item_id = ANY($1::uuid[]) ORDER BY ig.item_id, ig.sort_order, g.name
`

type ListGenresForItemsRow struct {
	ItemID uuid.UUID
	ID     uuid.UUID
	Name   string
}

func (q *Queries) ListGenresForItems(ctx context.Context, ids []uuid.UUID) ([]ListGenresForItemsRow, error) {
	rows, err := q.db.Query(ctx, listGenresForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenresForItemsRow{}
	for rows.Next() {
		var i ListGenresForItemsRow
		if err := rows.Scan(&i.ItemID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesForItems = `-- name: ListImagesForItems :many
SELECT item_id, type, idx, source_url, local_path, tag, blurhash, width, height FROM images WHERE item_id = ANY($1::uuid[]) ORDER BY item_id, type, idx
`

func (q *Queries) ListImagesForItems(ctx context.Context, ids []uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImagesForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ItemID,
			&i.Type,
			&i.Idx,
			&i.SourceUrl,
			&i.LocalPath,
			&i.Tag,
			&i.Blurhash,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaSourcesForItems = `-- name: ListMediaSourcesForItems :many
SELECT id, item_id, name, container, size, bitrate, path_or_url, protocol, is_remote, probed_at, probe_error, etag, runtime_ticks FROM media_sources WHERE item_id = ANY($1::uuid[]) ORDER BY item_id, name, id
`

func (q *Queries) ListMediaSourcesForItems(ctx context.Context, ids []uuid.UUID) ([]MediaSource, error) {
	rows, err := q.db.Query(ctx, listMediaSourcesForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaSource{}
	for rows.Next() {
		var i MediaSource
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Name,
			&i.Container,
			&i.Size,
			&i.Bitrate,
			&i.PathOrUrl,
			&i.Protocol,
			&i.IsRemote,
			&i.ProbedAt,
			&i.ProbeError,
			&i.Etag,
			&i.RuntimeTicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaStreamsForSources = `-- name: ListMediaStreamsForSources :many
SELECT media_source_id, idx, type, codec, language, title, is_default, is_forced, is_external, width, height, bitrate, channels, channel_layout, video_range, profile, level, pixel_format, delivery_url, bit_depth, aspect_ratio, average_frame_rate, real_frame_rate, is_interlaced, color_transfer, color_primaries, color_space, color_range, video_range_type, dv_profile, dv_level, dv_bl_compat_id, sample_rate, is_hearing_impaired, is_original, time_base, dv_version_major, dv_version_minor, dv_rpu_present, dv_el_present, dv_bl_present FROM media_streams WHERE media_source_id = ANY($1::uuid[]) ORDER BY media_source_id, idx
`

func (q *Queries) ListMediaStreamsForSources(ctx context.Context, ids []uuid.UUID) ([]MediaStream, error) {
	rows, err := q.db.Query(ctx, listMediaStreamsForSources, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaStream{}
	for rows.Next() {
		var i MediaStream
		if err := rows.Scan(
			&i.MediaSourceID,
			&i.Idx,
			&i.Type,
			&i.Codec,
			&i.Language,
			&i.Title,
			&i.IsDefault,
			&i.IsForced,
			&i.IsExternal,
			&i.Width,
			&i.Height,
			&i.Bitrate,
			&i.Channels,
			&i.ChannelLayout,
			&i.VideoRange,
			&i.Profile,
			&i.Level,
			&i.PixelFormat,
			&i.DeliveryUrl,
			&i.BitDepth,
			&i.AspectRatio,
			&i.AverageFrameRate,
			&i.RealFrameRate,
			&i.IsInterlaced,
			&i.ColorTransfer,
			&i.ColorPrimaries,
			&i.ColorSpace,
			&i.ColorRange,
			&i.VideoRangeType,
			&i.DvProfile,
			&i.DvLevel,
			&i.DvBlCompatID,
			&i.SampleRate,
			&i.IsHearingImpaired,
			&i.IsOriginal,
			&i.TimeBase,
			&i.DvVersionMajor,
			&i.DvVersionMinor,
			&i.DvRpuPresent,
			&i.DvElPresent,
			&i.DvBlPresent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleForItems = `-- name: ListPeopleForItems :many
SELECT ip.item_id, p.id, p.name, p.image_url, ip.kind, ip.role, ip.sort_order
FROM item_people ip JOIN people p ON p.id = ip.person_id
WHERE ip.item_id = ANY($1::uuid[])
ORDER BY ip.item_id, CASE ip.kind WHEN 'Actor' THEN 0 WHEN 'GuestStar' THEN 1 WHEN 'Director' THEN 2 ELSE 3 END, ip.sort_order, p.name
`

type ListPeopleForItemsRow struct {
	ItemID    uuid.UUID
	ID        uuid.UUID
	Name      string
	ImageUrl  *string
	Kind      string
	Role      *string
	SortOrder int32
}

func (q *Queries) ListPeopleForItems(ctx context.Context, ids []uuid.UUID) ([]ListPeopleForItemsRow, error) {
	rows, err := q.db.Query(ctx, listPeopleForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeopleForItemsRow{}
	for rows.Next() {
		var i ListPeopleForItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.Kind,
			&i.Role,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudiosForItems = `-- name: ListStudiosForItems :many
SELECT ist.item_id, s.id, s.name FROM item_studios ist JOIN studios s ON s.id = ist.studio_id
WHERE ist.item_id = ANY($1::uuid[]) ORDER BY ist.item_id, ist.sort_order, s.name
`

type ListStudiosForItemsRow struct {
	ItemID uuid.UUID
	ID     uuid.UUID
	Name   string
}

func (q *Queries) ListStudiosForItems(ctx context.Context, ids []uuid.UUID) ([]ListStudiosForItemsRow, error) {
	rows, err := q.db.Query(ctx, listStudiosForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudiosForItemsRow{}
	for rows.Next() {
		var i ListStudiosForItemsRow
		if err := rows.Scan(&i.ItemID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mediaSummaryForItems = `-- name: MediaSummaryForItems :many
SELECT ms.item_id, ms.container,
       coalesce((SELECT max(s.width)  FROM media_streams s WHERE s.media_source_id = ms.id AND s.type = 'Video'), 0)::int AS width,
       coalesce((SELECT max(s.height) FROM media_streams s WHERE s.media_source_id = ms.id AND s.type = 'Video'), 0)::int AS height,
       EXISTS (SELECT 1 FROM media_streams s WHERE s.media_source_id = ms.id AND s.type = 'Subtitle') AS has_subtitles
FROM media_sources ms WHERE ms.item_id = ANY($1::uuid[])
`

type MediaSummaryForItemsRow struct {
	ItemID       uuid.UUID
	Container    *string
	Width        int32
	Height       int32
	HasSubtitles bool
}

// Per item: container, video size (0 when not probed yet, e.g. a .strm
// before first play) and whether any subtitle stream exists.
func (q *Queries) MediaSummaryForItems(ctx context.Context, ids []uuid.UUID) ([]MediaSummaryForItemsRow, error) {
	rows, err := q.db.Query(ctx, mediaSummaryForItems, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaSummaryForItemsRow{}
	for rows.Next() {
		var i MediaSummaryForItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Container,
			&i.Width,
			&i.Height,
			&i.HasSubtitles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unplayedEpisodeCounts = `-- name: UnplayedEpisodeCounts :many
SELECT a.ancestor AS item_id,
       count(*) AS total,
       count(*) FILTER (WHERE NOT coalesce(ud.played, false)) AS unplayed,
       max(a.date_created)::timestamptz AS last_added,
       coalesce(sum(a.runtime_ticks), 0)::bigint AS runtime_ticks
FROM (
    SELECT e.id, e.parent_id AS ancestor, e.date_created, e.runtime_ticks FROM items e
    WHERE e.type = 'Episode' AND e.missing_since IS NULL AND e.parent_id = ANY($1::uuid[])
    UNION ALL
    SELECT e.id, s.parent_id, e.date_created, e.runtime_ticks FROM items e JOIN items s ON s.id = e.parent_id
    WHERE e.type = 'Episode' AND e.missing_since IS NULL AND s.parent_id = ANY($1::uuid[])
) a
LEFT JOIN user_data ud ON ud.item_id = a.id AND ud.user_id = $2
GROUP BY a.ancestor
`

type UnplayedEpisodeCountsParams struct {
	Ids    []uuid.UUID
	UserID uuid.UUID
}

type UnplayedEpisodeCountsRow struct {
	ItemID       *uuid.UUID
	Total        int64
	Unplayed     int64
	LastAdded    time.Time
	RuntimeTicks int64
}

// For Series/Season UserData.UnplayedItemCount and RecursiveItemCount.
// Also the newest episode's date (DateLastMediaAdded) and the summed runtime
// (CumulativeRunTimeTicks).
func (q *Queries) UnplayedEpisodeCounts(ctx context.Context, arg UnplayedEpisodeCountsParams) ([]UnplayedEpisodeCountsRow, error) {
	rows, err := q.db.Query(ctx, unplayedEpisodeCounts, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnplayedEpisodeCountsRow{}
	for rows.Next() {
		var i UnplayedEpisodeCountsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Total,
			&i.Unplayed,
			&i.LastAdded,
			&i.RuntimeTicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
