// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countItemsByType = `-- name: CountItemsByType :many
SELECT type, count(*) AS n, count(*) FILTER (WHERE missing_since IS NOT NULL) AS missing
FROM items WHERE library_id = $1 GROUP BY type ORDER BY type
`

type CountItemsByTypeRow struct {
	Type    string
	N       int64
	Missing int64
}

func (q *Queries) CountItemsByType(ctx context.Context, libraryID uuid.UUID) ([]CountItemsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countItemsByType, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountItemsByTypeRow{}
	for rows.Next() {
		var i CountItemsByTypeRow
		if err := rows.Scan(&i.Type, &i.N, &i.Missing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dBNow = `-- name: DBNow :one
SELECT now()::timestamptz AS now
`

// The database clock; scan bookkeeping compares against now() values set by
// the database, so it must not use the app host's clock.
func (q *Queries) DBNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, dBNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const deleteChapters = `-- name: DeleteChapters :exec
DELETE FROM chapters WHERE item_id = $1
`

func (q *Queries) DeleteChapters(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChapters, itemID)
	return err
}

const deleteEmptySeasons = `-- name: DeleteEmptySeasons :execrows
DELETE FROM items s
WHERE s.library_id = $1 AND s.type = 'Season'
  AND NOT EXISTS (SELECT 1 FROM items c WHERE c.parent_id = s.id)
`

func (q *Queries) DeleteEmptySeasons(ctx context.Context, libraryID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmptySeasons, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmptySeries = `-- name: DeleteEmptySeries :execrows
DELETE FROM items s
WHERE s.library_id = $1 AND s.type = 'Series'
  AND NOT EXISTS (SELECT 1 FROM items c WHERE c.parent_id = s.id)
`

func (q *Queries) DeleteEmptySeries(ctx context.Context, libraryID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmptySeries, libraryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMediaSources = `-- name: DeleteMediaSources :exec
DELETE FROM media_sources WHERE item_id = $1
`

func (q *Queries) DeleteMediaSources(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaSources, itemID)
	return err
}

const deleteMissingBefore = `-- name: DeleteMissingBefore :execrows
DELETE FROM items WHERE library_id = $1 AND missing_since < $2
`

type DeleteMissingBeforeParams struct {
	LibraryID uuid.UUID
	Cutoff    *time.Time
}

func (q *Queries) DeleteMissingBefore(ctx context.Context, arg DeleteMissingBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMissingBefore, arg.LibraryID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableLibrariesExcept = `-- name: DisableLibrariesExcept :execrows
UPDATE libraries SET enabled = false
WHERE enabled AND kind <> 'stremio' AND NOT (id = ANY($1::uuid[]))
`

// Libraries no longer in config.yaml stop being listed and scanned. Stremio
// catalog libraries aren't in config; the catalog sync manages them.
func (q *Queries) DisableLibrariesExcept(ctx context.Context, keep []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, disableLibrariesExcept, keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureCollectionFolder = `-- name: EnsureCollectionFolder :one
INSERT INTO items (library_id, type, name, sort_name)
VALUES ($1, 'CollectionFolder', $2, $3)
ON CONFLICT (library_id) WHERE type = 'CollectionFolder'
DO UPDATE SET name = EXCLUDED.name, sort_name = EXCLUDED.sort_name
RETURNING id
`

type EnsureCollectionFolderParams struct {
	LibraryID uuid.UUID
	Name      string
	SortName  string
}

func (q *Queries) EnsureCollectionFolder(ctx context.Context, arg EnsureCollectionFolderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, ensureCollectionFolder, arg.LibraryID, arg.Name, arg.SortName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMediaSourceByItem = `-- name: GetMediaSourceByItem :one
SELECT id, item_id, name, container, size, bitrate, path_or_url, protocol, is_remote, probed_at, probe_error, etag, runtime_ticks FROM media_sources WHERE item_id = $1
`

func (q *Queries) GetMediaSourceByItem(ctx context.Context, itemID uuid.UUID) (MediaSource, error) {
	row := q.db.QueryRow(ctx, getMediaSourceByItem, itemID)
	var i MediaSource
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Name,
		&i.Container,
		&i.Size,
		&i.Bitrate,
		&i.PathOrUrl,
		&i.Protocol,
		&i.IsRemote,
		&i.ProbedAt,
		&i.ProbeError,
		&i.Etag,
		&i.RuntimeTicks,
	)
	return i, err
}

const getStrmItem = `-- name: GetStrmItem :one
SELECT id, source_kind, path, strm_url, etag FROM items
WHERE id = $1 AND source_kind = 'strm' AND strm_url IS NOT NULL AND missing_since IS NULL
`

type GetStrmItemRow struct {
	ID         uuid.UUID
	SourceKind string
	Path       *string
	StrmUrl    *string
	Etag       *string
}

// A .strm item, for probing its remote source at first play (TASKS P2.4b).
func (q *Queries) GetStrmItem(ctx context.Context, id uuid.UUID) (GetStrmItemRow, error) {
	row := q.db.QueryRow(ctx, getStrmItem, id)
	var i GetStrmItemRow
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.Path,
		&i.StrmUrl,
		&i.Etag,
	)
	return i, err
}

const insertChapter = `-- name: InsertChapter :exec
INSERT INTO chapters (item_id, idx, start_ticks, name) VALUES ($1, $2, $3, $4)
`

type InsertChapterParams struct {
	ItemID     uuid.UUID
	Idx        int32
	StartTicks int64
	Name       string
}

func (q *Queries) InsertChapter(ctx context.Context, arg InsertChapterParams) error {
	_, err := q.db.Exec(ctx, insertChapter,
		arg.ItemID,
		arg.Idx,
		arg.StartTicks,
		arg.Name,
	)
	return err
}

const insertMediaSource = `-- name: InsertMediaSource :one
INSERT INTO media_sources (item_id, name, container, size, bitrate, path_or_url, protocol, is_remote,
                           probed_at, probe_error, etag, runtime_ticks)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12)
RETURNING id
`

type InsertMediaSourceParams struct {
	ItemID       uuid.UUID
	Name         string
	Container    *string
	Size         *int64
	Bitrate      *int32
	PathOrUrl    string
	Protocol     string
	IsRemote     bool
	ProbedAt     *time.Time
	ProbeError   *string
	Etag         *string
	RuntimeTicks *int64
}

func (q *Queries) InsertMediaSource(ctx context.Context, arg InsertMediaSourceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMediaSource,
		arg.ItemID,
		arg.Name,
		arg.Container,
		arg.Size,
		arg.Bitrate,
		arg.PathOrUrl,
		arg.Protocol,
		arg.IsRemote,
		arg.ProbedAt,
		arg.ProbeError,
		arg.Etag,
		arg.RuntimeTicks,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertMediaStream = `-- name: InsertMediaStream :exec
INSERT INTO media_streams (media_source_id, idx, type, codec, language, title, is_default, is_forced,
                           is_hearing_impaired, is_original, is_external, width, height, bitrate,
                           channels, channel_layout, sample_rate, video_range, video_range_type,
                           profile, level, pixel_format, bit_depth, aspect_ratio, average_frame_rate,
                           real_frame_rate, is_interlaced, color_transfer, color_primaries, color_space,
                           color_range, dv_profile, dv_level, dv_bl_compat_id, time_base,
                           dv_version_major, dv_version_minor, dv_rpu_present, dv_el_present, dv_bl_present,
                           external_path)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11::text IS NOT NULL,
        $12, $13, $14, $15,
        $16, $17, $18,
        $19, $20, $21, $22,
        $23, $24, $25,
        $26, $27, $28,
        $29, $30, $31,
        $32, $33, $34, $35,
        $36, $37, $38,
        $39, $40,
        $11)
`

type InsertMediaStreamParams struct {
	MediaSourceID     uuid.UUID
	Idx               int32
	Type              string
	Codec             *string
	Language          *string
	Title             *string
	IsDefault         bool
	IsForced          bool
	IsHearingImpaired bool
	IsOriginal        bool
	ExternalPath      *string
	Width             *int32
	Height            *int32
	Bitrate           *int32
	Channels          *int32
	ChannelLayout     *string
	SampleRate        *int32
	VideoRange        *string
	VideoRangeType    *string
	Profile           *string
	Level             *float32
	PixelFormat       *string
	BitDepth          *int32
	AspectRatio       *string
	AverageFrameRate  *float32
	RealFrameRate     *float32
	IsInterlaced      bool
	ColorTransfer     *string
	ColorPrimaries    *string
	ColorSpace        *string
	ColorRange        *string
	DvProfile         *int32
	DvLevel           *int32
	DvBlCompatID      *int32
	TimeBase          *string
	DvVersionMajor    *int32
	DvVersionMinor    *int32
	DvRpuPresent      *bool
	DvElPresent       *bool
	DvBlPresent       *bool
}

func (q *Queries) InsertMediaStream(ctx context.Context, arg InsertMediaStreamParams) error {
	_, err := q.db.Exec(ctx, insertMediaStream,
		arg.MediaSourceID,
		arg.Idx,
		arg.Type,
		arg.Codec,
		arg.Language,
		arg.Title,
		arg.IsDefault,
		arg.IsForced,
		arg.IsHearingImpaired,
		arg.IsOriginal,
		arg.ExternalPath,
		arg.Width,
		arg.Height,
		arg.Bitrate,
		arg.Channels,
		arg.ChannelLayout,
		arg.SampleRate,
		arg.VideoRange,
		arg.VideoRangeType,
		arg.Profile,
		arg.Level,
		arg.PixelFormat,
		arg.BitDepth,
		arg.AspectRatio,
		arg.AverageFrameRate,
		arg.RealFrameRate,
		arg.IsInterlaced,
		arg.ColorTransfer,
		arg.ColorPrimaries,
		arg.ColorSpace,
		arg.ColorRange,
		arg.DvProfile,
		arg.DvLevel,
		arg.DvBlCompatID,
		arg.TimeBase,
		arg.DvVersionMajor,
		arg.DvVersionMinor,
		arg.DvRpuPresent,
		arg.DvElPresent,
		arg.DvBlPresent,
	)
	return err
}

const itemsNeedingSource = `-- name: ItemsNeedingSource :many
SELECT i.id, i.source_kind, i.path, i.strm_url, i.etag
FROM items i
LEFT JOIN media_sources ms ON ms.item_id = i.id
WHERE i.library_id = $1
  AND i.source_kind IN ('file', 'strm')
  AND i.missing_since IS NULL
  AND (ms.id IS NULL OR ms.etag IS DISTINCT FROM i.etag)
`

type ItemsNeedingSourceRow struct {
	ID         uuid.UUID
	SourceKind string
	Path       *string
	StrmUrl    *string
	Etag       *string
}

// Playable items whose media source is missing or was built from another
// version of the file/URL: local files need probing, .strm items an
// (unprobed) remote source.
func (q *Queries) ItemsNeedingSource(ctx context.Context, libraryID uuid.UUID) ([]ItemsNeedingSourceRow, error) {
	rows, err := q.db.Query(ctx, itemsNeedingSource, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemsNeedingSourceRow{}
	for rows.Next() {
		var i ItemsNeedingSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceKind,
			&i.Path,
			&i.StrmUrl,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChapters = `-- name: ListChapters :many
SELECT item_id, idx, start_ticks, name FROM chapters WHERE item_id = $1 ORDER BY idx
`

func (q *Queries) ListChapters(ctx context.Context, itemID uuid.UUID) ([]Chapter, error) {
	rows, err := q.db.Query(ctx, listChapters, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ItemID,
			&i.Idx,
			&i.StartTicks,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryItems = `-- name: ListLibraryItems :many
SELECT id, library_id, parent_id, top_parent_id, type, name, original_title, sort_name, forced_sort_name, index_number, index_number_end, parent_index_number, production_year, premiere_date, end_date, overview, tagline, official_rating, community_rating, critic_rating, runtime_ticks, provider_ids, source_kind, path, strm_url, stremio_ref, etag, date_created, date_modified, date_last_refreshed, is_missing, missing_since, metadata_refreshed_at, metadata_source, original_language FROM items WHERE library_id = $1 ORDER BY type, path NULLS FIRST, index_number NULLS FIRST
`

// For tests and admin views: every item of a library in a stable order.
func (q *Queries) ListLibraryItems(ctx context.Context, libraryID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listLibraryItems, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ParentID,
			&i.TopParentID,
			&i.Type,
			&i.Name,
			&i.OriginalTitle,
			&i.SortName,
			&i.ForcedSortName,
			&i.IndexNumber,
			&i.IndexNumberEnd,
			&i.ParentIndexNumber,
			&i.ProductionYear,
			&i.PremiereDate,
			&i.EndDate,
			&i.Overview,
			&i.Tagline,
			&i.OfficialRating,
			&i.CommunityRating,
			&i.CriticRating,
			&i.RuntimeTicks,
			&i.ProviderIds,
			&i.SourceKind,
			&i.Path,
			&i.StrmUrl,
			&i.StremioRef,
			&i.Etag,
			&i.DateCreated,
			&i.DateModified,
			&i.DateLastRefreshed,
			&i.IsMissing,
			&i.MissingSince,
			&i.MetadataRefreshedAt,
			&i.MetadataSource,
			&i.OriginalLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaStreams = `-- name: ListMediaStreams :many
SELECT media_source_id, idx, type, codec, language, title, is_default, is_forced, is_external, width, height, bitrate, channels, channel_layout, video_range, profile, level, pixel_format, delivery_url, bit_depth, aspect_ratio, average_frame_rate, real_frame_rate, is_interlaced, color_transfer, color_primaries, color_space, color_range, video_range_type, dv_profile, dv_level, dv_bl_compat_id, sample_rate, is_hearing_impaired, is_original, time_base, dv_version_major, dv_version_minor, dv_rpu_present, dv_el_present, dv_bl_present, external_path FROM media_streams WHERE media_source_id = $1 ORDER BY idx
`

func (q *Queries) ListMediaStreams(ctx context.Context, mediaSourceID uuid.UUID) ([]MediaStream, error) {
	rows, err := q.db.Query(ctx, listMediaStreams, mediaSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaStream{}
	for rows.Next() {
		var i MediaStream
		if err := rows.Scan(
			&i.MediaSourceID,
			&i.Idx,
			&i.Type,
			&i.Codec,
			&i.Language,
			&i.Title,
			&i.IsDefault,
			&i.IsForced,
			&i.IsExternal,
			&i.Width,
			&i.Height,
			&i.Bitrate,
			&i.Channels,
			&i.ChannelLayout,
			&i.VideoRange,
			&i.Profile,
			&i.Level,
			&i.PixelFormat,
			&i.DeliveryUrl,
			&i.BitDepth,
			&i.AspectRatio,
			&i.AverageFrameRate,
			&i.RealFrameRate,
			&i.IsInterlaced,
			&i.ColorTransfer,
			&i.ColorPrimaries,
			&i.ColorSpace,
			&i.ColorRange,
			&i.VideoRangeType,
			&i.DvProfile,
			&i.DvLevel,
			&i.DvBlCompatID,
			&i.SampleRate,
			&i.IsHearingImpaired,
			&i.IsOriginal,
			&i.TimeBase,
			&i.DvVersionMajor,
			&i.DvVersionMinor,
			&i.DvRpuPresent,
			&i.DvElPresent,
			&i.DvBlPresent,
			&i.ExternalPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnseenMissing = `-- name: MarkUnseenMissing :execrows
UPDATE items SET is_missing = true, missing_since = coalesce(missing_since, now())
WHERE library_id = $1
  AND path IS NOT NULL
  AND type IN ('Movie', 'Series', 'Episode')
  AND (date_last_refreshed IS NULL OR date_last_refreshed < $2)
`

type MarkUnseenMissingParams struct {
	LibraryID uuid.UUID
	ScanStart *time.Time
}

// Path items the scan that started at @scan_start didn't see.
func (q *Queries) MarkUnseenMissing(ctx context.Context, arg MarkUnseenMissingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUnseenMissing, arg.LibraryID, arg.ScanStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemRuntime = `-- name: SetItemRuntime :exec
UPDATE items SET runtime_ticks = $2 WHERE id = $1
`

type SetItemRuntimeParams struct {
	ID           uuid.UUID
	RuntimeTicks *int64
}

func (q *Queries) SetItemRuntime(ctx context.Context, arg SetItemRuntimeParams) error {
	_, err := q.db.Exec(ctx, setItemRuntime, arg.ID, arg.RuntimeTicks)
	return err
}

const upsertLibrary = `-- name: UpsertLibrary :one

INSERT INTO libraries (name, kind, paths) VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET kind = EXCLUDED.kind, paths = EXCLUDED.paths, enabled = true
RETURNING id, name, kind, paths, options, created_at, enabled
`

type UpsertLibraryParams struct {
	Name  string
	Kind  string
	Paths []string
}

// Scanner queries (TASKS P1.14).
func (q *Queries) UpsertLibrary(ctx context.Context, arg UpsertLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, upsertLibrary, arg.Name, arg.Kind, arg.Paths)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Paths,
		&i.Options,
		&i.CreatedAt,
		&i.Enabled,
	)
	return i, err
}

const upsertPathItem = `-- name: UpsertPathItem :one
INSERT INTO items (library_id, parent_id, top_parent_id, type, name, sort_name, source_kind,
                   path, strm_url, index_number, parent_index_number, production_year, etag,
                   date_last_refreshed)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11,
        $12, $13, now())
ON CONFLICT (library_id, path) WHERE path IS NOT NULL DO UPDATE SET
    parent_id           = EXCLUDED.parent_id,
    top_parent_id       = EXCLUDED.top_parent_id,
    type                = EXCLUDED.type,
    -- Once metadata is applied, its name/sort name/year win over the file name.
    name                = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.name ELSE items.name END,
    sort_name           = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.sort_name ELSE items.sort_name END,
    source_kind         = EXCLUDED.source_kind,
    strm_url            = EXCLUDED.strm_url,
    index_number        = EXCLUDED.index_number,
    parent_index_number = EXCLUDED.parent_index_number,
    production_year     = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.production_year ELSE items.production_year END,
    date_modified       = CASE WHEN items.etag IS DISTINCT FROM EXCLUDED.etag THEN now() ELSE items.date_modified END,
    etag                = EXCLUDED.etag,
    date_last_refreshed = now(),
    is_missing          = false,
    missing_since       = NULL
RETURNING id
`

type UpsertPathItemParams struct {
	LibraryID         uuid.UUID
	ParentID          *uuid.UUID
	TopParentID       *uuid.UUID
	Type              string
	Name              string
	SortName          string
	SourceKind        string
	Path              *string
	StrmUrl           *string
	IndexNumber       *int32
	ParentIndexNumber *int32
	ProductionYear    *int32
	Etag              *string
}

// Movies, Series and Episodes are keyed by path. Every upsert marks the item
// as seen now (date_last_refreshed) and clears any missing flag.
func (q *Queries) UpsertPathItem(ctx context.Context, arg UpsertPathItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPathItem,
		arg.LibraryID,
		arg.ParentID,
		arg.TopParentID,
		arg.Type,
		arg.Name,
		arg.SortName,
		arg.SourceKind,
		arg.Path,
		arg.StrmUrl,
		arg.IndexNumber,
		arg.ParentIndexNumber,
		arg.ProductionYear,
		arg.Etag,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSeason = `-- name: UpsertSeason :one
INSERT INTO items (library_id, parent_id, top_parent_id, type, name, sort_name, index_number, date_last_refreshed)
VALUES ($1, $2, $3, 'Season', $4, $5, $6, now())
ON CONFLICT (parent_id, index_number) WHERE type = 'Season' DO UPDATE SET
    name = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.name ELSE items.name END,
    sort_name = EXCLUDED.sort_name,
    date_last_refreshed = now(), is_missing = false, missing_since = NULL
RETURNING id
`

type UpsertSeasonParams struct {
	LibraryID   uuid.UUID
	ParentID    *uuid.UUID
	TopParentID *uuid.UUID
	Name        string
	SortName    string
	IndexNumber *int32
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSeason,
		arg.LibraryID,
		arg.ParentID,
		arg.TopParentID,
		arg.Name,
		arg.SortName,
		arg.IndexNumber,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
