// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const applyItemMetadata = `-- name: ApplyItemMetadata :exec
UPDATE items SET
    name                  = coalesce($1, name),
    sort_name             = coalesce($2, sort_name),
    original_title        = $3,
    original_language     = $4,
    overview              = $5,
    tagline               = $6,
    official_rating       = $7,
    community_rating      = $8,
    premiere_date         = $9,
    end_date              = $10,
    production_year       = coalesce($11, production_year),
    runtime_ticks         = coalesce(runtime_ticks, $12),
    provider_ids          = $13,
    metadata_source       = $14,
    metadata_refreshed_at = now()
WHERE id = $15
`

type ApplyItemMetadataParams struct {
	Name             *string
	SortName         *string
	OriginalTitle    *string
	OriginalLanguage *string
	Overview         *string
	Tagline          *string
	OfficialRating   *string
	CommunityRating  *float32
	PremiereDate     *time.Time
	EndDate          *time.Time
	ProductionYear   *int32
	RuntimeTicks     *int64
	ProviderIds      json.RawMessage
	MetadataSource   *string
	ID               uuid.UUID
}

// NULL arguments keep the current value (e.g. episode sort names stay
// number-based).
func (q *Queries) ApplyItemMetadata(ctx context.Context, arg ApplyItemMetadataParams) error {
	_, err := q.db.Exec(ctx, applyItemMetadata,
		arg.Name,
		arg.SortName,
		arg.OriginalTitle,
		arg.OriginalLanguage,
		arg.Overview,
		arg.Tagline,
		arg.OfficialRating,
		arg.CommunityRating,
		arg.PremiereDate,
		arg.EndDate,
		arg.ProductionYear,
		arg.RuntimeTicks,
		arg.ProviderIds,
		arg.MetadataSource,
		arg.ID,
	)
	return err
}

const deleteItemGenres = `-- name: DeleteItemGenres :exec
DELETE FROM item_genres WHERE item_id = $1
`

func (q *Queries) DeleteItemGenres(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemGenres, itemID)
	return err
}

const deleteItemPeople = `-- name: DeleteItemPeople :exec
DELETE FROM item_people WHERE item_id = $1
`

func (q *Queries) DeleteItemPeople(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemPeople, itemID)
	return err
}

const deleteItemStudios = `-- name: DeleteItemStudios :exec
DELETE FROM item_studios WHERE item_id = $1
`

func (q *Queries) DeleteItemStudios(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemStudios, itemID)
	return err
}

const deleteRemoteImages = `-- name: DeleteRemoteImages :exec
DELETE FROM images WHERE item_id = $1 AND local_path IS NULL
`

// Artwork from metadata providers; locally found images are kept.
func (q *Queries) DeleteRemoteImages(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRemoteImages, itemID)
	return err
}

const insertItemGenre = `-- name: InsertItemGenre :exec
INSERT INTO item_genres (item_id, genre_id, sort_order) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertItemGenreParams struct {
	ItemID    uuid.UUID
	GenreID   uuid.UUID
	SortOrder int32
}

func (q *Queries) InsertItemGenre(ctx context.Context, arg InsertItemGenreParams) error {
	_, err := q.db.Exec(ctx, insertItemGenre, arg.ItemID, arg.GenreID, arg.SortOrder)
	return err
}

const insertItemPerson = `-- name: InsertItemPerson :exec
INSERT INTO item_people (item_id, person_id, kind, role, sort_order) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertItemPersonParams struct {
	ItemID    uuid.UUID
	PersonID  uuid.UUID
	Kind      string
	Role      *string
	SortOrder int32
}

func (q *Queries) InsertItemPerson(ctx context.Context, arg InsertItemPersonParams) error {
	_, err := q.db.Exec(ctx, insertItemPerson,
		arg.ItemID,
		arg.PersonID,
		arg.Kind,
		arg.Role,
		arg.SortOrder,
	)
	return err
}

const insertItemStudio = `-- name: InsertItemStudio :exec
INSERT INTO item_studios (item_id, studio_id, sort_order) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertItemStudioParams struct {
	ItemID    uuid.UUID
	StudioID  uuid.UUID
	SortOrder int32
}

func (q *Queries) InsertItemStudio(ctx context.Context, arg InsertItemStudioParams) error {
	_, err := q.db.Exec(ctx, insertItemStudio, arg.ItemID, arg.StudioID, arg.SortOrder)
	return err
}

const itemsNeedingMetadata = `-- name: ItemsNeedingMetadata :many

SELECT id, type, name, production_year, path, parent_id, index_number, parent_index_number,
       provider_ids, metadata_source, premiere_date
FROM items
WHERE library_id = $1
  AND type IN ('Movie', 'Series', 'Season', 'Episode')
  AND missing_since IS NULL
  AND (metadata_refreshed_at IS NULL
       OR (metadata_source = 'none' AND metadata_refreshed_at < $2)
       OR (metadata_source <> 'none' AND metadata_refreshed_at < $3))
ORDER BY CASE type WHEN 'Movie' THEN 0 WHEN 'Series' THEN 1 WHEN 'Season' THEN 2 ELSE 3 END,
         parent_id NULLS FIRST, index_number NULLS FIRST, path
`

type ItemsNeedingMetadataParams struct {
	LibraryID       uuid.UUID
	UnmatchedBefore *time.Time
	MatchedBefore   *time.Time
}

type ItemsNeedingMetadataRow struct {
	ID                uuid.UUID
	Type              string
	Name              string
	ProductionYear    *int32
	Path              *string
	ParentID          *uuid.UUID
	IndexNumber       *int32
	ParentIndexNumber *int32
	ProviderIds       json.RawMessage
	MetadataSource    *string
	PremiereDate      *time.Time
}

// Metadata refresh queries (TASKS P1.16).
// Never refreshed, matched but stale, or unmatched and due for a retry.
// Series before Seasons before Episodes, so parents are matched first.
func (q *Queries) ItemsNeedingMetadata(ctx context.Context, arg ItemsNeedingMetadataParams) ([]ItemsNeedingMetadataRow, error) {
	rows, err := q.db.Query(ctx, itemsNeedingMetadata, arg.LibraryID, arg.UnmatchedBefore, arg.MatchedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemsNeedingMetadataRow{}
	for rows.Next() {
		var i ItemsNeedingMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.ProductionYear,
			&i.Path,
			&i.ParentID,
			&i.IndexNumber,
			&i.ParentIndexNumber,
			&i.ProviderIds,
			&i.MetadataSource,
			&i.PremiereDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemGenres = `-- name: ListItemGenres :many
SELECT g.name FROM item_genres ig JOIN genres g ON g.id = ig.genre_id WHERE ig.item_id = $1 ORDER BY ig.sort_order, g.name
`

func (q *Queries) ListItemGenres(ctx context.Context, itemID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listItemGenres, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemImages = `-- name: ListItemImages :many
SELECT item_id, type, idx, source_url, local_path, tag, blurhash, width, height FROM images WHERE item_id = $1 ORDER BY type, idx
`

func (q *Queries) ListItemImages(ctx context.Context, itemID uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, listItemImages, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ItemID,
			&i.Type,
			&i.Idx,
			&i.SourceUrl,
			&i.LocalPath,
			&i.Tag,
			&i.Blurhash,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemPeople = `-- name: ListItemPeople :many
SELECT p.id, p.name, p.provider_ids, p.image_url, ip.kind, ip.role, ip.sort_order
FROM item_people ip JOIN people p ON p.id = ip.person_id
WHERE ip.item_id = $1
ORDER BY CASE ip.kind WHEN 'Actor' THEN 0 WHEN 'GuestStar' THEN 1 WHEN 'Director' THEN 2 ELSE 3 END, ip.sort_order, p.name
`

type ListItemPeopleRow struct {
	ID          uuid.UUID
	Name        string
	ProviderIds json.RawMessage
	ImageUrl    *string
	Kind        string
	Role        *string
	SortOrder   int32
}

func (q *Queries) ListItemPeople(ctx context.Context, itemID uuid.UUID) ([]ListItemPeopleRow, error) {
	rows, err := q.db.Query(ctx, listItemPeople, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemPeopleRow{}
	for rows.Next() {
		var i ListItemPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderIds,
			&i.ImageUrl,
			&i.Kind,
			&i.Role,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemStudios = `-- name: ListItemStudios :many
SELECT s.name FROM item_studios ist JOIN studios s ON s.id = ist.studio_id WHERE ist.item_id = $1 ORDER BY ist.sort_order, s.name
`

func (q *Queries) ListItemStudios(ctx context.Context, itemID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listItemStudios, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMetadataUnmatched = `-- name: MarkMetadataUnmatched :exec
UPDATE items SET metadata_source = 'none', metadata_refreshed_at = now() WHERE id = $1
`

func (q *Queries) MarkMetadataUnmatched(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMetadataUnmatched, id)
	return err
}

const upsertGenre = `-- name: UpsertGenre :one
INSERT INTO genres (name) VALUES ($1) ON CONFLICT (name) DO UPDATE SET name = genres.name RETURNING id
`

func (q *Queries) UpsertGenre(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertGenre, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertImage = `-- name: UpsertImage :exec
INSERT INTO images (item_id, type, idx, source_url, tag) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (item_id, type, idx) DO UPDATE SET source_url = EXCLUDED.source_url, tag = EXCLUDED.tag
`

type UpsertImageParams struct {
	ItemID    uuid.UUID
	Type      string
	Idx       int32
	SourceUrl *string
	Tag       string
}

func (q *Queries) UpsertImage(ctx context.Context, arg UpsertImageParams) error {
	_, err := q.db.Exec(ctx, upsertImage,
		arg.ItemID,
		arg.Type,
		arg.Idx,
		arg.SourceUrl,
		arg.Tag,
	)
	return err
}

const upsertPerson = `-- name: UpsertPerson :exec
INSERT INTO people (id, name, provider_ids, image_url) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, provider_ids = EXCLUDED.provider_ids,
    image_url = coalesce(EXCLUDED.image_url, people.image_url), updated_at = now()
`

type UpsertPersonParams struct {
	ID          uuid.UUID
	Name        string
	ProviderIds json.RawMessage
	ImageUrl    *string
}

func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) error {
	_, err := q.db.Exec(ctx, upsertPerson,
		arg.ID,
		arg.Name,
		arg.ProviderIds,
		arg.ImageUrl,
	)
	return err
}

const upsertStudio = `-- name: UpsertStudio :one
INSERT INTO studios (name) VALUES ($1) ON CONFLICT (name) DO UPDATE SET name = studios.name RETURNING id
`

func (q *Queries) UpsertStudio(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertStudio, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
