// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AccessToken struct {
	TokenSha   []byte
	UserID     uuid.UUID
	DeviceID   string
	CreatedAt  time.Time
	LastUsedAt time.Time
	RevokedAt  *time.Time
}

type Chapter struct {
	ItemID     uuid.UUID
	Idx        int32
	StartTicks int64
	Name       string
}

type DebridAccount struct {
	ID        uuid.UUID
	Provider  string
	ApiKeyEnc []byte
	Enabled   bool
	Priority  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DebridTorrent struct {
	Provider  string
	InfoHash  string
	TorrentID string
	Status    string
	AddedAt   time.Time
	CheckedAt time.Time
}

type Device struct {
	ID           string
	UserID       uuid.UUID
	Name         string
	AppName      string
	AppVersion   string
	LastSeenAt   time.Time
	Capabilities json.RawMessage
}

type DisplayPreference struct {
	UserID    uuid.UUID
	PrefID    string
	Client    string
	Data      json.RawMessage
	UpdatedAt time.Time
}

type Genre struct {
	ID   uuid.UUID
	Name string
}

type Image struct {
	ItemID    uuid.UUID
	Type      string
	Idx       int32
	SourceUrl *string
	LocalPath *string
	Tag       string
	Blurhash  *string
	Width     *int32
	Height    *int32
}

type Item struct {
	ID                  uuid.UUID
	LibraryID           uuid.UUID
	ParentID            *uuid.UUID
	TopParentID         *uuid.UUID
	Type                string
	Name                string
	OriginalTitle       *string
	SortName            string
	ForcedSortName      *string
	IndexNumber         *int32
	IndexNumberEnd      *int32
	ParentIndexNumber   *int32
	ProductionYear      *int32
	PremiereDate        *time.Time
	EndDate             *time.Time
	Overview            *string
	Tagline             *string
	OfficialRating      *string
	CommunityRating     *float32
	CriticRating        *float32
	RuntimeTicks        *int64
	ProviderIds         json.RawMessage
	SourceKind          string
	Path                *string
	StrmUrl             *string
	StremioRef          json.RawMessage
	Etag                *string
	DateCreated         time.Time
	DateModified        time.Time
	DateLastRefreshed   *time.Time
	IsMissing           bool
	MissingSince        *time.Time
	MetadataRefreshedAt *time.Time
	MetadataSource      *string
	OriginalLanguage    *string
}

type ItemGenre struct {
	ItemID    uuid.UUID
	GenreID   uuid.UUID
	SortOrder int32
}

type ItemPerson struct {
	ItemID    uuid.UUID
	PersonID  uuid.UUID
	Kind      string
	Role      *string
	SortOrder int32
}

type ItemStudio struct {
	ItemID    uuid.UUID
	StudioID  uuid.UUID
	SortOrder int32
}

type Library struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	Paths     []string
	Options   json.RawMessage
	CreatedAt time.Time
	Enabled   bool
	Position  int32
	Hidden    bool
}

type MediaSource struct {
	ID           uuid.UUID
	ItemID       uuid.UUID
	Name         string
	Container    *string
	Size         *int64
	Bitrate      *int32
	PathOrUrl    string
	Protocol     string
	IsRemote     bool
	ProbedAt     *time.Time
	ProbeError   *string
	Etag         *string
	RuntimeTicks *int64
}

type MediaStream struct {
	MediaSourceID     uuid.UUID
	Idx               int32
	Type              string
	Codec             *string
	Language          *string
	Title             *string
	IsDefault         bool
	IsForced          bool
	IsExternal        bool
	Width             *int32
	Height            *int32
	Bitrate           *int32
	Channels          *int32
	ChannelLayout     *string
	VideoRange        *string
	Profile           *string
	Level             *float32
	PixelFormat       *string
	DeliveryUrl       *string
	BitDepth          *int32
	AspectRatio       *string
	AverageFrameRate  *float32
	RealFrameRate     *float32
	IsInterlaced      bool
	ColorTransfer     *string
	ColorPrimaries    *string
	ColorSpace        *string
	ColorRange        *string
	VideoRangeType    *string
	DvProfile         *int32
	DvLevel           *int32
	DvBlCompatID      *int32
	SampleRate        *int32
	IsHearingImpaired bool
	IsOriginal        bool
	TimeBase          *string
	DvVersionMajor    *int32
	DvVersionMinor    *int32
	DvRpuPresent      *bool
	DvElPresent       *bool
	DvBlPresent       *bool
	ExternalPath      *string
}

type Person struct {
	ID          uuid.UUID
	Name        string
	ProviderIds json.RawMessage
	ImageUrl    *string
	UpdatedAt   time.Time
}

type PlaybackLog struct {
	ID            int64
	UserID        *uuid.UUID
	UserName      string
	DeviceName    string
	Client        string
	ItemID        uuid.UUID
	ItemName      string
	RuntimeTicks  *int64
	PlaySessionID *string
	PlayMethod    string
	SourceName    string
	Addon         string
	Delivery      string
	LinkHost      string
	Bytes         int64
	PositionTicks int64
	StartedAt     time.Time
	LastSeenAt    time.Time
	StoppedAt     *time.Time
}

type ProxiedBytesMonthly struct {
	Month time.Time
	Bytes int64
}

type ServerSetting struct {
	Key       string
	Value     json.RawMessage
	UpdatedAt time.Time
}

type StremioAddon struct {
	ID            uuid.UUID
	UrlEnc        []byte
	UrlSha        []byte
	Host          string
	Manifest      json.RawMessage
	Enabled       bool
	Priority      int32
	LastFetchedAt time.Time
	CreatedAt     time.Time
}

type StremioCatalog struct {
	AddonID     uuid.UUID
	CatalogType string
	CatalogID   string
	Name        string
	LibraryID   *uuid.UUID
	Enabled     bool
}

type Studio struct {
	ID   uuid.UUID
	Name string
}

type User struct {
	ID            uuid.UUID
	Name          string
	PasswordHash  *string
	IsAdmin       bool
	IsDisabled    bool
	Policy        json.RawMessage
	Configuration json.RawMessage
	CreatedAt     time.Time
	LastLoginAt   *time.Time
}

type UserDatum struct {
	UserID                uuid.UUID
	ItemID                uuid.UUID
	Played                bool
	PlayCount             int32
	PlaybackPositionTicks int64
	IsFavorite            bool
	Rating                *float32
	LastPlayedAt          *time.Time
	AudioStreamIdx        *int32
	SubtitleStreamIdx     *int32
	UpdatedAt             time.Time
}
