// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playbacklog.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPlaybackBytes = `-- name: AddPlaybackBytes :exec
UPDATE playback_log
SET bytes = bytes + $1, last_seen_at = now()
WHERE play_session_id = $2
`

type AddPlaybackBytesParams struct {
	Bytes         int64
	PlaySessionID *string
}

// Bytes blockbustr proxied for a play session's stream.
func (q *Queries) AddPlaybackBytes(ctx context.Context, arg AddPlaybackBytesParams) error {
	_, err := q.db.Exec(ctx, addPlaybackBytes, arg.Bytes, arg.PlaySessionID)
	return err
}

const listPlaybackLog = `-- name: ListPlaybackLog :many
SELECT id, user_id, user_name, device_name, client, item_id, item_name, runtime_ticks, play_method,
       source_name, addon, delivery, link_host, bytes, position_ticks, started_at, last_seen_at, stopped_at
FROM playback_log
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListPlaybackLogParams struct {
	UserID   *uuid.UUID
	BeforeID int64
	Lim      int32
}

type ListPlaybackLogRow struct {
	ID            int64
	UserID        *uuid.UUID
	UserName      string
	DeviceName    string
	Client        string
	ItemID        uuid.UUID
	ItemName      string
	RuntimeTicks  *int64
	PlayMethod    string
	SourceName    string
	Addon         string
	Delivery      string
	LinkHost      string
	Bytes         int64
	PositionTicks int64
	StartedAt     time.Time
	LastSeenAt    time.Time
	StoppedAt     *time.Time
}

// The newest plays first, before the id given (0: from the newest), for
// one user or (no user_id) everyone.
func (q *Queries) ListPlaybackLog(ctx context.Context, arg ListPlaybackLogParams) ([]ListPlaybackLogRow, error) {
	rows, err := q.db.Query(ctx, listPlaybackLog, arg.UserID, arg.BeforeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaybackLogRow{}
	for rows.Next() {
		var i ListPlaybackLogRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.DeviceName,
			&i.Client,
			&i.ItemID,
			&i.ItemName,
			&i.RuntimeTicks,
			&i.PlayMethod,
			&i.SourceName,
			&i.Addon,
			&i.Delivery,
			&i.LinkHost,
			&i.Bytes,
			&i.PositionTicks,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playbackTotals = `-- name: PlaybackTotals :many
SELECT user_id, user_name,
       count(*)::bigint AS plays,
       coalesce(sum(extract(epoch FROM coalesce(stopped_at, last_seen_at) - started_at)), 0)::bigint AS seconds,
       coalesce(sum(bytes), 0)::bigint AS bytes,
       max(started_at)::timestamptz AS last_played
FROM playback_log
WHERE started_at >= $1
GROUP BY user_id, user_name
ORDER BY plays DESC, user_name
`

type PlaybackTotalsRow struct {
	UserID     *uuid.UUID
	UserName   string
	Plays      int64
	Seconds    int64
	Bytes      int64
	LastPlayed time.Time
}

// Per user since a time: plays, time spent playing (start to stop, or to
// the last report of a play that never stopped) and bytes proxied.
func (q *Queries) PlaybackTotals(ctx context.Context, since time.Time) ([]PlaybackTotalsRow, error) {
	rows, err := q.db.Query(ctx, playbackTotals, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaybackTotalsRow{}
	for rows.Next() {
		var i PlaybackTotalsRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.Plays,
			&i.Seconds,
			&i.Bytes,
			&i.LastPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prunePlaybackLog = `-- name: PrunePlaybackLog :execrows
DELETE FROM playback_log WHERE started_at < $1
`

func (q *Queries) PrunePlaybackLog(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, prunePlaybackLog, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePlaybackProgress = `-- name: UpdatePlaybackProgress :exec
UPDATE playback_log
SET position_ticks = $1,
    play_method    = coalesce(nullif($2::text, ''), play_method),
    last_seen_at   = now(),
    stopped_at     = CASE WHEN $3::boolean THEN now() ELSE stopped_at END
WHERE id = $4
`

type UpdatePlaybackProgressParams struct {
	PositionTicks int64
	PlayMethod    string
	Stopped       bool
	ID            int64
}

// Progress and stop reports of a logged play.
func (q *Queries) UpdatePlaybackProgress(ctx context.Context, arg UpdatePlaybackProgressParams) error {
	_, err := q.db.Exec(ctx, updatePlaybackProgress,
		arg.PositionTicks,
		arg.PlayMethod,
		arg.Stopped,
		arg.ID,
	)
	return err
}

const upsertPlayback = `-- name: UpsertPlayback :one
INSERT INTO playback_log (user_id, user_name, device_name, client, item_id, item_name, runtime_ticks,
                          play_session_id, play_method, source_name, addon, delivery, link_host)
SELECT u.id, u.name, $1, $2, i.id,
       CASE WHEN i.type = 'Episode' THEN
              coalesce(CASE WHEN p.type = 'Series' THEN p.name WHEN g.type = 'Series' THEN g.name END || ' ', '')
              || 'S' || lpad(coalesce(i.parent_index_number, 0)::text, 2, '0')
              || 'E' || lpad(coalesce(i.index_number, 0)::text, 2, '0') || ' · ' || i.name
            ELSE i.name || coalesce(' (' || i.production_year || ')', '') END,
       i.runtime_ticks, $3, $4, $5, $6, $7, $8
FROM items i
JOIN users u ON u.id = $9
LEFT JOIN items p ON p.id = i.parent_id
LEFT JOIN items g ON g.id = p.parent_id
WHERE i.id = $10
ON CONFLICT (play_session_id) WHERE play_session_id IS NOT NULL DO UPDATE
SET device_name  = coalesce(nullif(EXCLUDED.device_name, ''), playback_log.device_name),
    client       = coalesce(nullif(EXCLUDED.client, ''), playback_log.client),
    play_method  = coalesce(nullif(EXCLUDED.play_method, ''), playback_log.play_method),
    source_name  = coalesce(nullif(EXCLUDED.source_name, ''), playback_log.source_name),
    addon        = coalesce(nullif(EXCLUDED.addon, ''), playback_log.addon),
    delivery     = coalesce(nullif(EXCLUDED.delivery, ''), playback_log.delivery),
    link_host    = coalesce(nullif(EXCLUDED.link_host, ''), playback_log.link_host),
    last_seen_at = now(),
    stopped_at   = CASE WHEN $11::boolean THEN NULL ELSE playback_log.stopped_at END
RETURNING id
`

type UpsertPlaybackParams struct {
	DeviceName    string
	Client        string
	PlaySessionID *string
	PlayMethod    string
	SourceName    string
	Addon         string
	Delivery      string
	LinkHost      string
	UserID        uuid.UUID
	ItemID        uuid.UUID
	Reopen        bool
}

// A play begins (the Playing report) or its stream is requested; the two
// meet on the play session id when the client sends one. Non-empty values
// replace stored ones, so the report adds the device and play method and
// the stream request what was played and how. reopen (a Playing report)
// clears an earlier stop. No row when the item or user doesn't exist.
func (q *Queries) UpsertPlayback(ctx context.Context, arg UpsertPlaybackParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertPlayback,
		arg.DeviceName,
		arg.Client,
		arg.PlaySessionID,
		arg.PlayMethod,
		arg.SourceName,
		arg.Addon,
		arg.Delivery,
		arg.LinkHost,
		arg.UserID,
		arg.ItemID,
		arg.Reopen,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
