// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxiedbytes.sql

package db

import (
	"context"
	"time"
)

const addProxiedBytes = `-- name: AddProxiedBytes :exec
INSERT INTO proxied_bytes_monthly (month, bytes) VALUES ($1, $2)
ON CONFLICT (month) DO UPDATE SET bytes = proxied_bytes_monthly.bytes + EXCLUDED.bytes
`

type AddProxiedBytesParams struct {
	Month time.Time
	Bytes int64
}

// Adds to a month's total (month: its first day).
func (q *Queries) AddProxiedBytes(ctx context.Context, arg AddProxiedBytesParams) error {
	_, err := q.db.Exec(ctx, addProxiedBytes, arg.Month, arg.Bytes)
	return err
}

const listProxiedBytes = `-- name: ListProxiedBytes :many
SELECT month, bytes FROM proxied_bytes_monthly ORDER BY month DESC LIMIT $1
`

// The newest months first.
func (q *Queries) ListProxiedBytes(ctx context.Context, lim int32) ([]ProxiedBytesMonthly, error) {
	rows, err := q.db.Query(ctx, listProxiedBytes, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxiedBytesMonthly{}
	for rows.Next() {
		var i ProxiedBytesMonthly
		if err := rows.Scan(&i.Month, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
