// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxiedbytes.sql

package db

import (
	"context"
	"time"
)

const addProxiedBytes = `-- name: AddProxiedBytes :exec
INSERT INTO proxied_bytes_hourly (hour, bytes) VALUES ($1, $2)
ON CONFLICT (hour) DO UPDATE SET bytes = proxied_bytes_hourly.bytes + EXCLUDED.bytes
`

type AddProxiedBytesParams struct {
	Hour  time.Time
	Bytes int64
}

// Adds to an hour's total (hour: its start).
func (q *Queries) AddProxiedBytes(ctx context.Context, arg AddProxiedBytesParams) error {
	_, err := q.db.Exec(ctx, addProxiedBytes, arg.Hour, arg.Bytes)
	return err
}

const listProxiedBytesByMonth = `-- name: ListProxiedBytesByMonth :many
SELECT to_char(date_trunc('month', hour AT TIME ZONE $1::text), 'YYYY-MM')::text AS month,
       sum(bytes)::bigint AS bytes
FROM proxied_bytes_hourly
GROUP BY 1
ORDER BY 1 DESC
LIMIT $2
`

type ListProxiedBytesByMonthParams struct {
	Tz  string
	Lim int32
}

type ListProxiedBytesByMonthRow struct {
	Month string
	Bytes int64
}

// The newest calendar months first, as they fall in the time zone tz (an
// IANA name).
func (q *Queries) ListProxiedBytesByMonth(ctx context.Context, arg ListProxiedBytesByMonthParams) ([]ListProxiedBytesByMonthRow, error) {
	rows, err := q.db.Query(ctx, listProxiedBytesByMonth, arg.Tz, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProxiedBytesByMonthRow{}
	for rows.Next() {
		var i ListProxiedBytesByMonthRow
		if err := rows.Scan(&i.Month, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
