// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
	"encoding/json"
)

const getSetting = `-- name: GetSetting :one
SELECT value FROM server_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const insertSettingIfMissing = `-- name: InsertSettingIfMissing :exec
INSERT INTO server_settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
`

type InsertSettingIfMissingParams struct {
	Key   string
	Value json.RawMessage
}

// First writer wins, so concurrent starts agree on generated values.
func (q *Queries) InsertSettingIfMissing(ctx context.Context, arg InsertSettingIfMissingParams) error {
	_, err := q.db.Exec(ctx, insertSettingIfMissing, arg.Key, arg.Value)
	return err
}
