// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shows.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const nextUpEpisodeIDs = `-- name: NextUpEpisodeIDs :many

WITH episodes AS (
    SELECT i.id, coalesce(s.parent_id, i.parent_id) AS series_id,
           i.parent_index_number AS season, i.index_number AS number, i.premiere_date
    FROM items i
    JOIN libraries l ON l.id = i.library_id
    LEFT JOIN items s ON s.id = i.parent_id AND s.type = 'Season'
    WHERE i.type = 'Episode' AND i.missing_since IS NULL AND l.enabled
), started AS (
    SELECT e.series_id, max(ud.last_played_at) AS last_played
    FROM user_data ud
    JOIN episodes e ON e.id = ud.item_id
    WHERE ud.user_id = $3
    GROUP BY e.series_id
    HAVING bool_or(ud.played OR ud.play_count > 0 OR ud.playback_position_ticks > 0)
), picked AS (
    SELECT DISTINCT ON (e.series_id) e.id, e.series_id, st.last_played
    FROM episodes e
    JOIN started st ON st.series_id = e.series_id
    LEFT JOIN user_data ud ON ud.item_id = e.id AND ud.user_id = $3
    WHERE NOT coalesce(ud.played, false)
      AND ($4::date IS NULL OR e.premiere_date IS NULL OR e.premiere_date <= $4)
      AND ($5::uuid IS NULL OR e.series_id = $5)
      -- without @include_resumable, half-watched episodes are skipped
      AND ($6::boolean OR coalesce(ud.playback_position_ticks, 0) = 0)
    -- with it, the earliest half-watched episode wins over unwatched ones
    ORDER BY e.series_id, coalesce(ud.playback_position_ticks, 0) > 0 DESC,
             coalesce(e.season, -1), coalesce(e.number, -1), e.id
)
SELECT p.id, count(*) OVER () AS total
FROM picked p
ORDER BY p.last_played DESC NULLS LAST,
         (SELECT lower(coalesce(sr.forced_sort_name, sr.sort_name)) FROM items sr WHERE sr.id = p.series_id),
         p.series_id
LIMIT $2 OFFSET $1
`

type NextUpEpisodeIDsParams struct {
	StartIdx         int32
	Lim              int32
	UserID           uuid.UUID
	Cutoff           *time.Time
	SeriesID         *uuid.UUID
	IncludeResumable bool
}

type NextUpEpisodeIDsRow struct {
	ID    uuid.UUID
	Total int64
}

// Shows and home-screen queries (TASKS P1.21).
// The next episode to watch per series (TASKS P1.21, observed on 12.1.0):
// the episode being rewatched (the earliest half-watched one) when
// @include_resumable is set, else the earliest unplayed episode that isn't
// half-watched — but only for series the user has started (some episode
// played, begun or re-watched). Ordered by the series' most recent
// activity, then the series' sort name. total (a window count over the
// whole result) fills TotalRecordCount when the page is full.
// Started series are found first and one episode is picked per series
// (DISTINCT ON), so the cost grows with the library, not its square
// (TASKS P4.5: 9 s at 19.5k episodes before).
func (q *Queries) NextUpEpisodeIDs(ctx context.Context, arg NextUpEpisodeIDsParams) ([]NextUpEpisodeIDsRow, error) {
	rows, err := q.db.Query(ctx, nextUpEpisodeIDs,
		arg.StartIdx,
		arg.Lim,
		arg.UserID,
		arg.Cutoff,
		arg.SeriesID,
		arg.IncludeResumable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextUpEpisodeIDsRow{}
	for rows.Next() {
		var i NextUpEpisodeIDsRow
		if err := rows.Scan(&i.ID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const similarItemIDs = `-- name: SimilarItemIDs :many
SELECT i.id
FROM items i
JOIN libraries l ON l.id = i.library_id
WHERE l.enabled AND i.missing_since IS NULL
  AND i.type = $1 AND i.id <> $2
ORDER BY (3 * (SELECT count(*) FROM item_genres a JOIN item_genres b ON b.genre_id = a.genre_id
               WHERE a.item_id = $2 AND b.item_id = i.id)
        + 2 * (SELECT count(*) FROM item_studios a JOIN item_studios b ON b.studio_id = a.studio_id
               WHERE a.item_id = $2 AND b.item_id = i.id)
        + (SELECT count(*) FROM item_people a JOIN item_people b ON b.person_id = a.person_id
           WHERE a.item_id = $2 AND b.item_id = i.id)) DESC,
         abs(coalesce(i.production_year, 0) - coalesce((SELECT s.production_year FROM items s WHERE s.id = $2), 0)),
         coalesce(i.forced_sort_name, i.sort_name)
LIMIT $3
`

type SimilarItemIDsParams struct {
	Typ    string
	ItemID uuid.UUID
	Lim    int32
}

// Every other item of the same kind, most similar first (TASKS P1.21;
// Jellyfin's /Items/{id}/Similar also lists items that share nothing).
// Scored 3 points per shared genre, 2 per studio, 1 per person, ties broken
// by the closer production year, then the sort name. The handler only asks
// for Movie and Series; other kinds have no similar items.
func (q *Queries) SimilarItemIDs(ctx context.Context, arg SimilarItemIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, similarItemIDs, arg.Typ, arg.ItemID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
