// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shows.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const nextUpEpisodeIDs = `-- name: NextUpEpisodeIDs :many

WITH candidates AS (
    SELECT i.id,
           coalesce((SELECT s.parent_id FROM items s WHERE s.id = i.parent_id AND s.type = 'Season'), i.parent_id) AS series_id,
           i.parent_index_number AS season, i.index_number AS number,
           coalesce(ud.playback_position_ticks, 0) > 0 AS resumable
    FROM items i
    JOIN libraries l ON l.id = i.library_id
    LEFT JOIN user_data ud ON ud.item_id = i.id AND ud.user_id = $1
    WHERE i.type = 'Episode' AND i.missing_since IS NULL AND l.enabled
      AND NOT coalesce(ud.played, false)
      AND ($4::date IS NULL OR i.premiere_date IS NULL OR i.premiere_date <= $4)
), ranked AS (
    SELECT c.id, c.series_id, c.season, c.number, c.resumable, count(*) OVER () AS total
    FROM candidates c
    WHERE ($5::uuid IS NULL OR c.series_id = $5)
      AND (
          -- the earliest half-watched episode of the series
          ($6::boolean AND c.resumable AND NOT EXISTS (
              SELECT 1 FROM candidates e
              WHERE e.series_id = c.series_id AND e.resumable
                AND (coalesce(e.season, -1), coalesce(e.number, -1)) < (coalesce(c.season, -1), coalesce(c.number, -1))))
          OR
          -- else the earliest unplayed episode nobody is halfway through,
          -- unless @include_resumable already picked the resumed one above
          (NOT c.resumable
           AND NOT ($6::boolean AND EXISTS (SELECT 1 FROM candidates e WHERE e.series_id = c.series_id AND e.resumable))
           AND NOT EXISTS (
              SELECT 1 FROM candidates e
              WHERE e.series_id = c.series_id AND NOT e.resumable
                AND (coalesce(e.season, -1), coalesce(e.number, -1)) < (coalesce(c.season, -1), coalesce(c.number, -1)))))
      -- only series the user has started
      AND EXISTS (
          SELECT 1 FROM items p2
          JOIN user_data pu2 ON pu2.item_id = p2.id AND pu2.user_id = $1
          WHERE p2.type = 'Episode' AND p2.missing_since IS NULL
            AND coalesce((SELECT s3.parent_id FROM items s3 WHERE s3.id = p2.parent_id AND s3.type = 'Season'), p2.parent_id) = c.series_id
            AND (pu2.played OR pu2.play_count > 0 OR pu2.playback_position_ticks > 0))
)
SELECT r.id, r.total
FROM ranked r
ORDER BY (SELECT max(pu3.last_played_at)
          FROM user_data pu3 JOIN items p3 ON p3.id = pu3.item_id
          WHERE pu3.user_id = $1 AND p3.type = 'Episode' AND p3.missing_since IS NULL
            AND coalesce((SELECT s4.parent_id FROM items s4 WHERE s4.id = p3.parent_id AND s4.type = 'Season'), p3.parent_id) = r.series_id) DESC NULLS LAST,
         (SELECT lower(coalesce(sr.forced_sort_name, sr.sort_name)) FROM items sr WHERE sr.id = r.series_id),
         r.series_id, r.season NULLS FIRST, r.number NULLS FIRST
LIMIT $3 OFFSET $2
`

type NextUpEpisodeIDsParams struct {
	UserID           uuid.UUID
	StartIdx         int32
	Lim              int32
	Cutoff           *time.Time
	SeriesID         *uuid.UUID
	IncludeResumable bool
}

type NextUpEpisodeIDsRow struct {
	ID    uuid.UUID
	Total int64
}

// Shows and home-screen queries (TASKS P1.21).
// The next episode to watch per series (TASKS P1.21, observed on 12.1.0):
// the episode being rewatched (the earliest half-watched one) when
// @include_resumable is set, else the earliest unplayed episode that isn't
// half-watched — but only for series the user has started (some episode
// played, begun or re-watched). Ordered by the series' most recent
// activity, then the series' sort name. total (a window count over the
// whole result) fills TotalRecordCount when the page is full.
func (q *Queries) NextUpEpisodeIDs(ctx context.Context, arg NextUpEpisodeIDsParams) ([]NextUpEpisodeIDsRow, error) {
	rows, err := q.db.Query(ctx, nextUpEpisodeIDs,
		arg.UserID,
		arg.StartIdx,
		arg.Lim,
		arg.Cutoff,
		arg.SeriesID,
		arg.IncludeResumable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextUpEpisodeIDsRow{}
	for rows.Next() {
		var i NextUpEpisodeIDsRow
		if err := rows.Scan(&i.ID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const similarItemIDs = `-- name: SimilarItemIDs :many
SELECT i.id
FROM items i
JOIN libraries l ON l.id = i.library_id
WHERE l.enabled AND i.missing_since IS NULL
  AND i.type = $1 AND i.id <> $2
ORDER BY (3 * (SELECT count(*) FROM item_genres a JOIN item_genres b ON b.genre_id = a.genre_id
               WHERE a.item_id = $2 AND b.item_id = i.id)
        + 2 * (SELECT count(*) FROM item_studios a JOIN item_studios b ON b.studio_id = a.studio_id
               WHERE a.item_id = $2 AND b.item_id = i.id)
        + (SELECT count(*) FROM item_people a JOIN item_people b ON b.person_id = a.person_id
           WHERE a.item_id = $2 AND b.item_id = i.id)) DESC,
         abs(coalesce(i.production_year, 0) - coalesce((SELECT s.production_year FROM items s WHERE s.id = $2), 0)),
         coalesce(i.forced_sort_name, i.sort_name)
LIMIT $3
`

type SimilarItemIDsParams struct {
	Typ    string
	ItemID uuid.UUID
	Lim    int32
}

// Every other item of the same kind, most similar first (TASKS P1.21;
// Jellyfin's /Items/{id}/Similar also lists items that share nothing).
// Scored 3 points per shared genre, 2 per studio, 1 per person, ties broken
// by the closer production year, then the sort name. The handler only asks
// for Movie and Series; other kinds have no similar items.
func (q *Queries) SimilarItemIDs(ctx context.Context, arg SimilarItemIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, similarItemIDs, arg.Typ, arg.ItemID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
