// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stremio.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteStremioAddon = `-- name: DeleteStremioAddon :execrows
DELETE FROM stremio_addons WHERE id = $1
`

func (q *Queries) DeleteStremioAddon(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStremioAddon, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStremioCatalogsExcept = `-- name: DeleteStremioCatalogsExcept :exec
DELETE FROM stremio_catalogs
WHERE addon_id = $1 AND NOT (catalog_type || '/' || catalog_id = ANY ($2::text[]))
`

type DeleteStremioCatalogsExceptParams struct {
	AddonID uuid.UUID
	Keep    []string
}

// Drops catalogs the manifest no longer lists; keep holds "type/id" keys.
func (q *Queries) DeleteStremioCatalogsExcept(ctx context.Context, arg DeleteStremioCatalogsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteStremioCatalogsExcept, arg.AddonID, arg.Keep)
	return err
}

const getStremioAddon = `-- name: GetStremioAddon :one
SELECT id, url_enc, url_sha, host, manifest, enabled, priority, last_fetched_at, created_at FROM stremio_addons WHERE id = $1
`

func (q *Queries) GetStremioAddon(ctx context.Context, id uuid.UUID) (StremioAddon, error) {
	row := q.db.QueryRow(ctx, getStremioAddon, id)
	var i StremioAddon
	err := row.Scan(
		&i.ID,
		&i.UrlEnc,
		&i.UrlSha,
		&i.Host,
		&i.Manifest,
		&i.Enabled,
		&i.Priority,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertStremioAddon = `-- name: InsertStremioAddon :one
INSERT INTO stremio_addons (url_enc, url_sha, host, manifest, priority)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (url_sha) DO NOTHING
RETURNING id, url_enc, url_sha, host, manifest, enabled, priority, last_fetched_at, created_at
`

type InsertStremioAddonParams struct {
	UrlEnc   []byte
	UrlSha   []byte
	Host     string
	Manifest json.RawMessage
	Priority int32
}

// A configuration already added (same url_sha) returns no row.
func (q *Queries) InsertStremioAddon(ctx context.Context, arg InsertStremioAddonParams) (StremioAddon, error) {
	row := q.db.QueryRow(ctx, insertStremioAddon,
		arg.UrlEnc,
		arg.UrlSha,
		arg.Host,
		arg.Manifest,
		arg.Priority,
	)
	var i StremioAddon
	err := row.Scan(
		&i.ID,
		&i.UrlEnc,
		&i.UrlSha,
		&i.Host,
		&i.Manifest,
		&i.Enabled,
		&i.Priority,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listStremioAddons = `-- name: ListStremioAddons :many
SELECT id, url_enc, url_sha, host, manifest, enabled, priority, last_fetched_at, created_at FROM stremio_addons ORDER BY priority DESC, created_at
`

func (q *Queries) ListStremioAddons(ctx context.Context) ([]StremioAddon, error) {
	rows, err := q.db.Query(ctx, listStremioAddons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StremioAddon{}
	for rows.Next() {
		var i StremioAddon
		if err := rows.Scan(
			&i.ID,
			&i.UrlEnc,
			&i.UrlSha,
			&i.Host,
			&i.Manifest,
			&i.Enabled,
			&i.Priority,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStremioCatalogs = `-- name: ListStremioCatalogs :many
SELECT addon_id, catalog_type, catalog_id, name, library_id, enabled FROM stremio_catalogs WHERE addon_id = $1 ORDER BY catalog_type, catalog_id
`

func (q *Queries) ListStremioCatalogs(ctx context.Context, addonID uuid.UUID) ([]StremioCatalog, error) {
	rows, err := q.db.Query(ctx, listStremioCatalogs, addonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StremioCatalog{}
	for rows.Next() {
		var i StremioCatalog
		if err := rows.Scan(
			&i.AddonID,
			&i.CatalogType,
			&i.CatalogID,
			&i.Name,
			&i.LibraryID,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStremioAddonManifest = `-- name: SetStremioAddonManifest :exec
UPDATE stremio_addons SET manifest = $2, last_fetched_at = now() WHERE id = $1
`

type SetStremioAddonManifestParams struct {
	ID       uuid.UUID
	Manifest json.RawMessage
}

func (q *Queries) SetStremioAddonManifest(ctx context.Context, arg SetStremioAddonManifestParams) error {
	_, err := q.db.Exec(ctx, setStremioAddonManifest, arg.ID, arg.Manifest)
	return err
}

const setStremioCatalogEnabled = `-- name: SetStremioCatalogEnabled :execrows
UPDATE stremio_catalogs SET enabled = $4
WHERE addon_id = $1 AND catalog_type = $2 AND catalog_id = $3
`

type SetStremioCatalogEnabledParams struct {
	AddonID     uuid.UUID
	CatalogType string
	CatalogID   string
	Enabled     bool
}

func (q *Queries) SetStremioCatalogEnabled(ctx context.Context, arg SetStremioCatalogEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStremioCatalogEnabled,
		arg.AddonID,
		arg.CatalogType,
		arg.CatalogID,
		arg.Enabled,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStremioAddon = `-- name: UpdateStremioAddon :one
UPDATE stremio_addons SET enabled = $2, priority = $3 WHERE id = $1 RETURNING id, url_enc, url_sha, host, manifest, enabled, priority, last_fetched_at, created_at
`

type UpdateStremioAddonParams struct {
	ID       uuid.UUID
	Enabled  bool
	Priority int32
}

func (q *Queries) UpdateStremioAddon(ctx context.Context, arg UpdateStremioAddonParams) (StremioAddon, error) {
	row := q.db.QueryRow(ctx, updateStremioAddon, arg.ID, arg.Enabled, arg.Priority)
	var i StremioAddon
	err := row.Scan(
		&i.ID,
		&i.UrlEnc,
		&i.UrlSha,
		&i.Host,
		&i.Manifest,
		&i.Enabled,
		&i.Priority,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertStremioCatalog = `-- name: UpsertStremioCatalog :exec
INSERT INTO stremio_catalogs (addon_id, catalog_type, catalog_id, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (addon_id, catalog_type, catalog_id) DO UPDATE SET name = EXCLUDED.name
`

type UpsertStremioCatalogParams struct {
	AddonID     uuid.UUID
	CatalogType string
	CatalogID   string
	Name        string
}

// A refreshed manifest renames a catalog but keeps its enabled flag and
// library.
func (q *Queries) UpsertStremioCatalog(ctx context.Context, arg UpsertStremioCatalogParams) error {
	_, err := q.db.Exec(ctx, upsertStremioCatalog,
		arg.AddonID,
		arg.CatalogType,
		arg.CatalogID,
		arg.Name,
	)
	return err
}
