// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stremio.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createStremioLibrary = `-- name: CreateStremioLibrary :one
INSERT INTO libraries (name, kind, options) VALUES ($1, 'stremio', $2)
ON CONFLICT (name) DO NOTHING
RETURNING id, name, kind, paths, options, created_at, enabled
`

type CreateStremioLibraryParams struct {
	Name    string
	Options json.RawMessage
}

// A name already taken returns no row; the caller tries another.
func (q *Queries) CreateStremioLibrary(ctx context.Context, arg CreateStremioLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, createStremioLibrary, arg.Name, arg.Options)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Paths,
		&i.Options,
		&i.CreatedAt,
		&i.Enabled,
	)
	return i, err
}

const deleteStaleDiscoverItems = `-- name: DeleteStaleDiscoverItems :execrows
DELETE FROM items i
USING libraries l
WHERE l.id = i.library_id AND l.kind = 'discover' AND i.parent_id IS NULL
  AND coalesce(i.date_last_refreshed, i.date_created) < $1
  AND NOT EXISTS (
    SELECT 1 FROM user_data ud JOIN items d ON d.id = ud.item_id
    WHERE (ud.played OR ud.is_favorite OR ud.playback_position_ticks > 0)
      AND (d.id = i.id OR d.parent_id = i.id
           OR d.parent_id IN (SELECT s.id FROM items s WHERE s.parent_id = i.id)))
`

// Discover titles nobody kept: not found by a search since @before and with
// no user data (played, favourite, in progress) on them or their episodes.
func (q *Queries) DeleteStaleDiscoverItems(ctx context.Context, before *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleDiscoverItems, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStremioAddon = `-- name: DeleteStremioAddon :execrows
DELETE FROM stremio_addons WHERE id = $1
`

func (q *Queries) DeleteStremioAddon(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStremioAddon, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStremioCatalogsExcept = `-- name: DeleteStremioCatalogsExcept :exec
DELETE FROM stremio_catalogs
WHERE addon_id = $1 AND NOT (catalog_type || '/' || catalog_id = ANY ($2::text[]))
`

type DeleteStremioCatalogsExceptParams struct {
	AddonID uuid.UUID
	Keep    []string
}

// Drops catalogs the manifest no longer lists; keep holds "type/id" keys.
func (q *Queries) DeleteStremioCatalogsExcept(ctx context.Context, arg DeleteStremioCatalogsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteStremioCatalogsExcept, arg.AddonID, arg.Keep)
	return err
}

const ensureDiscoverLibrary = `-- name: EnsureDiscoverLibrary :one
INSERT INTO libraries (name, kind) VALUES ('blockbustr:discover', 'discover')
ON CONFLICT (name) DO UPDATE SET kind = 'discover', enabled = true
RETURNING id, name, kind, paths, options, created_at, enabled
`

// The hidden library search results are stored in (P3.13); its name can't
// clash with a configured library's.
func (q *Queries) EnsureDiscoverLibrary(ctx context.Context) (Library, error) {
	row := q.db.QueryRow(ctx, ensureDiscoverLibrary)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Paths,
		&i.Options,
		&i.CreatedAt,
		&i.Enabled,
	)
	return i, err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, kind, paths, options, created_at, enabled FROM libraries WHERE id = $1
`

func (q *Queries) GetLibrary(ctx context.Context, id uuid.UUID) (Library, error) {
	row := q.db.QueryRow(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Paths,
		&i.Options,
		&i.CreatedAt,
		&i.Enabled,
	)
	return i, err
}

const getStremioAddon = `-- name: GetStremioAddon :one
SELECT id, url_enc, url_sha, host, manifest, enabled, priority, last_fetched_at, created_at FROM stremio_addons WHERE id = $1
`

func (q *Queries) GetStremioAddon(ctx context.Context, id uuid.UUID) (StremioAddon, error) {
	row := q.db.QueryRow(ctx, getStremioAddon, id)
	var i StremioAddon
	err := row.Scan(
		&i.ID,
		&i.UrlEnc,
		&i.UrlSha,
		&i.Host,
		&i.Manifest,
		&i.Enabled,
		&i.Priority,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertStremioAddon = `-- name: InsertStremioAddon :one
INSERT INTO stremio_addons (url_enc, url_sha, host, manifest, priority)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (url_sha) DO NOTHING
RETURNING id, url_enc, url_sha, host, manifest, enabled, priority, last_fetched_at, created_at
`

type InsertStremioAddonParams struct {
	UrlEnc   []byte
	UrlSha   []byte
	Host     string
	Manifest json.RawMessage
	Priority int32
}

// A configuration already added (same url_sha) returns no row.
func (q *Queries) InsertStremioAddon(ctx context.Context, arg InsertStremioAddonParams) (StremioAddon, error) {
	row := q.db.QueryRow(ctx, insertStremioAddon,
		arg.UrlEnc,
		arg.UrlSha,
		arg.Host,
		arg.Manifest,
		arg.Priority,
	)
	var i StremioAddon
	err := row.Scan(
		&i.ID,
		&i.UrlEnc,
		&i.UrlSha,
		&i.Host,
		&i.Manifest,
		&i.Enabled,
		&i.Priority,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const libraryItemsByImdb = `-- name: LibraryItemsByImdb :many
SELECT i.id, i.library_id, i.parent_id, i.top_parent_id, i.type, i.name, i.original_title, i.sort_name, i.forced_sort_name, i.index_number, i.index_number_end, i.parent_index_number, i.production_year, i.premiere_date, i.end_date, i.overview, i.tagline, i.official_rating, i.community_rating, i.critic_rating, i.runtime_ticks, i.provider_ids, i.source_kind, i.path, i.strm_url, i.stremio_ref, i.etag, i.date_created, i.date_modified, i.date_last_refreshed, i.is_missing, i.missing_since, i.metadata_refreshed_at, i.metadata_source, i.original_language FROM items i JOIN libraries l ON l.id = i.library_id
WHERE l.enabled AND l.kind <> 'discover' AND i.missing_since IS NULL
  AND i.type = ANY($1::text[]) AND i.provider_ids ->> 'Imdb' = ANY($2::text[])
`

type LibraryItemsByImdbParams struct {
	Types []string
	Imdb  []string
}

// Titles already in an enabled library (not discover) with these IMDb ids:
// search shows those instead of a discover copy.
func (q *Queries) LibraryItemsByImdb(ctx context.Context, arg LibraryItemsByImdbParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, libraryItemsByImdb, arg.Types, arg.Imdb)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ParentID,
			&i.TopParentID,
			&i.Type,
			&i.Name,
			&i.OriginalTitle,
			&i.SortName,
			&i.ForcedSortName,
			&i.IndexNumber,
			&i.IndexNumberEnd,
			&i.ParentIndexNumber,
			&i.ProductionYear,
			&i.PremiereDate,
			&i.EndDate,
			&i.Overview,
			&i.Tagline,
			&i.OfficialRating,
			&i.CommunityRating,
			&i.CriticRating,
			&i.RuntimeTicks,
			&i.ProviderIds,
			&i.SourceKind,
			&i.Path,
			&i.StrmUrl,
			&i.StremioRef,
			&i.Etag,
			&i.DateCreated,
			&i.DateModified,
			&i.DateLastRefreshed,
			&i.IsMissing,
			&i.MissingSince,
			&i.MetadataRefreshedAt,
			&i.MetadataSource,
			&i.OriginalLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStremioAddons = `-- name: ListStremioAddons :many
SELECT id, url_enc, url_sha, host, manifest, enabled, priority, last_fetched_at, created_at FROM stremio_addons ORDER BY priority DESC, created_at
`

func (q *Queries) ListStremioAddons(ctx context.Context) ([]StremioAddon, error) {
	rows, err := q.db.Query(ctx, listStremioAddons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StremioAddon{}
	for rows.Next() {
		var i StremioAddon
		if err := rows.Scan(
			&i.ID,
			&i.UrlEnc,
			&i.UrlSha,
			&i.Host,
			&i.Manifest,
			&i.Enabled,
			&i.Priority,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStremioCatalogs = `-- name: ListStremioCatalogs :many
SELECT addon_id, catalog_type, catalog_id, name, library_id, enabled FROM stremio_catalogs WHERE addon_id = $1 ORDER BY catalog_type, catalog_id
`

func (q *Queries) ListStremioCatalogs(ctx context.Context, addonID uuid.UUID) ([]StremioCatalog, error) {
	rows, err := q.db.Query(ctx, listStremioCatalogs, addonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StremioCatalog{}
	for rows.Next() {
		var i StremioCatalog
		if err := rows.Scan(
			&i.AddonID,
			&i.CatalogType,
			&i.CatalogID,
			&i.Name,
			&i.LibraryID,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncCatalogs = `-- name: ListSyncCatalogs :many

SELECT c.addon_id, c.catalog_type, c.catalog_id, c.name, c.library_id, c.enabled,
       a.enabled AS addon_enabled
FROM stremio_catalogs c JOIN stremio_addons a ON a.id = c.addon_id
WHERE (c.enabled AND a.enabled) OR c.library_id IS NOT NULL
ORDER BY a.priority DESC, a.created_at, c.catalog_type, c.catalog_id
`

type ListSyncCatalogsRow struct {
	AddonID      uuid.UUID
	CatalogType  string
	CatalogID    string
	Name         string
	LibraryID    *uuid.UUID
	Enabled      bool
	AddonEnabled bool
}

// Catalog sync (P3.5).
// Every catalog of an enabled addon that is enabled or still has a library
// (to switch that library off).
func (q *Queries) ListSyncCatalogs(ctx context.Context) ([]ListSyncCatalogsRow, error) {
	rows, err := q.db.Query(ctx, listSyncCatalogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncCatalogsRow{}
	for rows.Next() {
		var i ListSyncCatalogsRow
		if err := rows.Scan(
			&i.AddonID,
			&i.CatalogType,
			&i.CatalogID,
			&i.Name,
			&i.LibraryID,
			&i.Enabled,
			&i.AddonEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLibraryEnabled = `-- name: SetLibraryEnabled :exec
UPDATE libraries SET enabled = $1 WHERE id = $2 AND enabled IS DISTINCT FROM $1
`

type SetLibraryEnabledParams struct {
	Enabled bool
	ID      uuid.UUID
}

func (q *Queries) SetLibraryEnabled(ctx context.Context, arg SetLibraryEnabledParams) error {
	_, err := q.db.Exec(ctx, setLibraryEnabled, arg.Enabled, arg.ID)
	return err
}

const setStremioAddonManifest = `-- name: SetStremioAddonManifest :exec
UPDATE stremio_addons SET manifest = $2, last_fetched_at = now() WHERE id = $1
`

type SetStremioAddonManifestParams struct {
	ID       uuid.UUID
	Manifest json.RawMessage
}

func (q *Queries) SetStremioAddonManifest(ctx context.Context, arg SetStremioAddonManifestParams) error {
	_, err := q.db.Exec(ctx, setStremioAddonManifest, arg.ID, arg.Manifest)
	return err
}

const setStremioCatalogEnabled = `-- name: SetStremioCatalogEnabled :execrows
UPDATE stremio_catalogs SET enabled = $4
WHERE addon_id = $1 AND catalog_type = $2 AND catalog_id = $3
`

type SetStremioCatalogEnabledParams struct {
	AddonID     uuid.UUID
	CatalogType string
	CatalogID   string
	Enabled     bool
}

func (q *Queries) SetStremioCatalogEnabled(ctx context.Context, arg SetStremioCatalogEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStremioCatalogEnabled,
		arg.AddonID,
		arg.CatalogType,
		arg.CatalogID,
		arg.Enabled,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStremioCatalogLibrary = `-- name: SetStremioCatalogLibrary :exec
UPDATE stremio_catalogs SET library_id = $4
WHERE addon_id = $1 AND catalog_type = $2 AND catalog_id = $3
`

type SetStremioCatalogLibraryParams struct {
	AddonID     uuid.UUID
	CatalogType string
	CatalogID   string
	LibraryID   *uuid.UUID
}

func (q *Queries) SetStremioCatalogLibrary(ctx context.Context, arg SetStremioCatalogLibraryParams) error {
	_, err := q.db.Exec(ctx, setStremioCatalogLibrary,
		arg.AddonID,
		arg.CatalogType,
		arg.CatalogID,
		arg.LibraryID,
	)
	return err
}

const touchStremioEpisodes = `-- name: TouchStremioEpisodes :exec
UPDATE items SET date_last_refreshed = now()
WHERE library_id = $1 AND type = 'Episode' AND missing_since IS NULL
  AND starts_with(path, $2::text)
`

type TouchStremioEpisodesParams struct {
	LibraryID uuid.UUID
	Prefix    string
}

// Keeps a series' episodes when its meta couldn't be fetched this sync, so
// an addon hiccup doesn't mark them missing.
func (q *Queries) TouchStremioEpisodes(ctx context.Context, arg TouchStremioEpisodesParams) error {
	_, err := q.db.Exec(ctx, touchStremioEpisodes, arg.LibraryID, arg.Prefix)
	return err
}

const updateStremioAddon = `-- name: UpdateStremioAddon :one
UPDATE stremio_addons SET enabled = $2, priority = $3 WHERE id = $1 RETURNING id, url_enc, url_sha, host, manifest, enabled, priority, last_fetched_at, created_at
`

type UpdateStremioAddonParams struct {
	ID       uuid.UUID
	Enabled  bool
	Priority int32
}

func (q *Queries) UpdateStremioAddon(ctx context.Context, arg UpdateStremioAddonParams) (StremioAddon, error) {
	row := q.db.QueryRow(ctx, updateStremioAddon, arg.ID, arg.Enabled, arg.Priority)
	var i StremioAddon
	err := row.Scan(
		&i.ID,
		&i.UrlEnc,
		&i.UrlSha,
		&i.Host,
		&i.Manifest,
		&i.Enabled,
		&i.Priority,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDiscoverItem = `-- name: UpsertDiscoverItem :one
INSERT INTO items (id, library_id, type, name, sort_name, source_kind, path, stremio_ref,
                   production_year, premiere_date, overview, provider_ids, date_last_refreshed)
VALUES ($1, $2, $3, $4, $5, 'stremio', $6, $7,
        $8, $9, $10, $11, now())
ON CONFLICT (library_id, path) WHERE path IS NOT NULL DO UPDATE SET
    stremio_ref     = EXCLUDED.stremio_ref,
    name            = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.name ELSE items.name END,
    sort_name       = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.sort_name ELSE items.sort_name END,
    production_year = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.production_year ELSE items.production_year END,
    overview        = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN coalesce(EXCLUDED.overview, items.overview) ELSE items.overview END,
    provider_ids    = items.provider_ids || EXCLUDED.provider_ids,
    date_last_refreshed = now(),
    is_missing      = false,
    missing_since   = NULL
RETURNING id, (coalesce(metadata_source, 'none') = 'none')::boolean AS catalog_owned
`

type UpsertDiscoverItemParams struct {
	ID             uuid.UUID
	LibraryID      uuid.UUID
	Type           string
	Name           string
	SortName       string
	Path           *string
	StremioRef     json.RawMessage
	ProductionYear *int32
	PremiereDate   *time.Time
	Overview       *string
	ProviderIds    json.RawMessage
}

type UpsertDiscoverItemRow struct {
	ID           uuid.UUID
	CatalogOwned bool
}

// A search result, keyed by path like a catalog title but with the id the
// caller derives (UUIDv5 of its IMDb id), so the same title always has the
// same id even after it was cleaned up and found again. Searching it again
// keeps it (date_last_refreshed).
func (q *Queries) UpsertDiscoverItem(ctx context.Context, arg UpsertDiscoverItemParams) (UpsertDiscoverItemRow, error) {
	row := q.db.QueryRow(ctx, upsertDiscoverItem,
		arg.ID,
		arg.LibraryID,
		arg.Type,
		arg.Name,
		arg.SortName,
		arg.Path,
		arg.StremioRef,
		arg.ProductionYear,
		arg.PremiereDate,
		arg.Overview,
		arg.ProviderIds,
	)
	var i UpsertDiscoverItemRow
	err := row.Scan(&i.ID, &i.CatalogOwned)
	return i, err
}

const upsertStremioCatalog = `-- name: UpsertStremioCatalog :exec
INSERT INTO stremio_catalogs (addon_id, catalog_type, catalog_id, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (addon_id, catalog_type, catalog_id) DO UPDATE SET name = EXCLUDED.name
`

type UpsertStremioCatalogParams struct {
	AddonID     uuid.UUID
	CatalogType string
	CatalogID   string
	Name        string
}

// A refreshed manifest renames a catalog but keeps its enabled flag and
// library.
func (q *Queries) UpsertStremioCatalog(ctx context.Context, arg UpsertStremioCatalogParams) error {
	_, err := q.db.Exec(ctx, upsertStremioCatalog,
		arg.AddonID,
		arg.CatalogType,
		arg.CatalogID,
		arg.Name,
	)
	return err
}

const upsertStremioItem = `-- name: UpsertStremioItem :one
INSERT INTO items (library_id, parent_id, top_parent_id, type, name, sort_name, source_kind,
                   path, stremio_ref, index_number, parent_index_number, production_year,
                   premiere_date, overview, provider_ids, date_last_refreshed)
VALUES ($1, $2, $3, $4, $5, $6, 'stremio',
        $7, $8, $9, $10,
        $11, $12, $13, $14, now())
ON CONFLICT (library_id, path) WHERE path IS NOT NULL DO UPDATE SET
    parent_id           = EXCLUDED.parent_id,
    top_parent_id       = EXCLUDED.top_parent_id,
    type                = EXCLUDED.type,
    stremio_ref         = EXCLUDED.stremio_ref,
    index_number        = EXCLUDED.index_number,
    parent_index_number = EXCLUDED.parent_index_number,
    name            = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.name ELSE items.name END,
    sort_name       = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.sort_name ELSE items.sort_name END,
    production_year = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.production_year ELSE items.production_year END,
    premiere_date   = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.premiere_date ELSE items.premiere_date END,
    overview        = CASE WHEN coalesce(items.metadata_source, 'none') = 'none' THEN EXCLUDED.overview ELSE items.overview END,
    provider_ids        = items.provider_ids || EXCLUDED.provider_ids,
    date_last_refreshed = now(),
    is_missing          = false,
    missing_since       = NULL
RETURNING id, (coalesce(metadata_source, 'none') = 'none')::boolean AS catalog_owned
`

type UpsertStremioItemParams struct {
	LibraryID         uuid.UUID
	ParentID          *uuid.UUID
	TopParentID       *uuid.UUID
	Type              string
	Name              string
	SortName          string
	Path              *string
	StremioRef        json.RawMessage
	IndexNumber       *int32
	ParentIndexNumber *int32
	ProductionYear    *int32
	PremiereDate      *time.Time
	Overview          *string
	ProviderIds       json.RawMessage
}

type UpsertStremioItemRow struct {
	ID           uuid.UUID
	CatalogOwned bool
}

// Catalog titles and their episodes, keyed by path ("stremio:{type}:{id}").
// Like UpsertPathItem, metadata applied later (TMDB) wins over the
// catalog's name/year/overview; provider ids from the catalog are merged in.
func (q *Queries) UpsertStremioItem(ctx context.Context, arg UpsertStremioItemParams) (UpsertStremioItemRow, error) {
	row := q.db.QueryRow(ctx, upsertStremioItem,
		arg.LibraryID,
		arg.ParentID,
		arg.TopParentID,
		arg.Type,
		arg.Name,
		arg.SortName,
		arg.Path,
		arg.StremioRef,
		arg.IndexNumber,
		arg.ParentIndexNumber,
		arg.ProductionYear,
		arg.PremiereDate,
		arg.Overview,
		arg.ProviderIds,
	)
	var i UpsertStremioItemRow
	err := row.Scan(&i.ID, &i.CatalogOwned)
	return i, err
}
