// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO access_tokens (token_sha, user_id, device_id) VALUES ($1, $2, $3)
`

type CreateAccessTokenParams struct {
	TokenSha []byte
	UserID   uuid.UUID
	DeviceID string
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createAccessToken, arg.TokenSha, arg.UserID, arg.DeviceID)
	return err
}

const getTokenSession = `-- name: GetTokenSession :one
SELECT t.user_id, t.device_id, u.name AS user_name, u.is_admin,
       d.name AS device_name, d.app_name, d.app_version
FROM access_tokens t
JOIN users   u ON u.id = t.user_id
JOIN devices d ON d.id = t.device_id
WHERE t.token_sha = $1
  AND t.revoked_at IS NULL
  AND NOT u.is_disabled
`

type GetTokenSessionRow struct {
	UserID     uuid.UUID
	DeviceID   string
	UserName   string
	IsAdmin    bool
	DeviceName string
	AppName    string
	AppVersion string
}

// Resolves a token (sha256) to its user and device. Revoked tokens and
// disabled users don't resolve.
func (q *Queries) GetTokenSession(ctx context.Context, tokenSha []byte) (GetTokenSessionRow, error) {
	row := q.db.QueryRow(ctx, getTokenSession, tokenSha)
	var i GetTokenSessionRow
	err := row.Scan(
		&i.UserID,
		&i.DeviceID,
		&i.UserName,
		&i.IsAdmin,
		&i.DeviceName,
		&i.AppName,
		&i.AppVersion,
	)
	return i, err
}

const revokeAccessToken = `-- name: RevokeAccessToken :execrows
UPDATE access_tokens SET revoked_at = now() WHERE token_sha = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAccessToken(ctx context.Context, tokenSha []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccessToken, tokenSha)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDeviceTokens = `-- name: RevokeDeviceTokens :execrows
UPDATE access_tokens SET revoked_at = now() WHERE device_id = $1 AND revoked_at IS NULL
`

// Jellyfin signs a device out of older sessions when it logs in again.
func (q *Queries) RevokeDeviceTokens(ctx context.Context, deviceID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceTokens, deviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAccessToken = `-- name: TouchAccessToken :exec
UPDATE access_tokens SET last_used_at = now() WHERE token_sha = $1
`

func (q *Queries) TouchAccessToken(ctx context.Context, tokenSha []byte) error {
	_, err := q.db.Exec(ctx, touchAccessToken, tokenSha)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (id, user_id, name, app_name, app_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET user_id      = EXCLUDED.user_id,
    name         = EXCLUDED.name,
    app_name     = EXCLUDED.app_name,
    app_version  = EXCLUDED.app_version,
    last_seen_at = now()
`

type UpsertDeviceParams struct {
	ID         string
	UserID     uuid.UUID
	Name       string
	AppName    string
	AppVersion string
}

// A device belongs to whichever user last signed in on it (DESIGN §4).
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.AppName,
		arg.AppVersion,
	)
	return err
}
