// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: userbytes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUserBytes = `-- name: AddUserBytes :exec
INSERT INTO user_bytes_hourly (user_id, hour, bytes) VALUES ($1, $2, $3)
ON CONFLICT (user_id, hour) DO UPDATE SET bytes = user_bytes_hourly.bytes + EXCLUDED.bytes
`

type AddUserBytesParams struct {
	UserID uuid.UUID
	Hour   time.Time
	Bytes  int64
}

// Adds to a user's total for an hour (hour: its start).
func (q *Queries) AddUserBytes(ctx context.Context, arg AddUserBytesParams) error {
	_, err := q.db.Exec(ctx, addUserBytes, arg.UserID, arg.Hour, arg.Bytes)
	return err
}

const pruneUserBytes = `-- name: PruneUserBytes :execrows
DELETE FROM user_bytes_hourly WHERE hour < $1
`

func (q *Queries) PruneUserBytes(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneUserBytes, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userBytesByUserSince = `-- name: UserBytesByUserSince :many
SELECT user_id, sum(bytes)::bigint AS bytes
FROM user_bytes_hourly
WHERE hour >= $1
GROUP BY user_id
`

type UserBytesByUserSinceRow struct {
	UserID uuid.UUID
	Bytes  int64
}

// Every user's proxied bytes since a time, for the admin UI.
func (q *Queries) UserBytesByUserSince(ctx context.Context, since time.Time) ([]UserBytesByUserSinceRow, error) {
	rows, err := q.db.Query(ctx, userBytesByUserSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBytesByUserSinceRow{}
	for rows.Next() {
		var i UserBytesByUserSinceRow
		if err := rows.Scan(&i.UserID, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userBytesSince = `-- name: UserBytesSince :one
SELECT coalesce(sum(bytes), 0)::bigint AS bytes
FROM user_bytes_hourly
WHERE user_id = $1 AND hour >= $2
`

type UserBytesSinceParams struct {
	UserID uuid.UUID
	Since  time.Time
}

// A user's proxied bytes since a time (the start of their quota month).
func (q *Queries) UserBytesSince(ctx context.Context, arg UserBytesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, userBytesSince, arg.UserID, arg.Since)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}
