// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countEnabledAdmins = `-- name: CountEnabledAdmins :one
SELECT count(*) FROM users WHERE is_admin AND NOT is_disabled
`

func (q *Queries) CountEnabledAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, password_hash, is_admin)
VALUES ($1, $2, $3)
RETURNING id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at
`

type CreateUserParams struct {
	Name         string
	PasswordHash *string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.PasswordHash, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.Policy,
		&i.Configuration,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

// Tokens, devices and user data go with the user (ON DELETE CASCADE).
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.Policy,
		&i.Configuration,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at FROM users WHERE name = $1
`

// users.name is citext, so this is case-insensitive like Jellyfin's login.
func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.Policy,
		&i.Configuration,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.IsDisabled,
			&i.Policy,
			&i.Configuration,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameUser = `-- name: RenameUser :one
UPDATE users SET name = $2 WHERE id = $1 RETURNING id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at
`

type RenameUserParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RenameUser(ctx context.Context, arg RenameUserParams) (User, error) {
	row := q.db.QueryRow(ctx, renameUser, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.Policy,
		&i.Configuration,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const resetAdminCredentials = `-- name: ResetAdminCredentials :exec
UPDATE users SET password_hash = $2, is_admin = true, is_disabled = false WHERE id = $1
`

type ResetAdminCredentialsParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

// Bootstrap/recovery: (re)set the configured admin's password and make sure
// it is an enabled administrator.
func (q *Queries) ResetAdminCredentials(ctx context.Context, arg ResetAdminCredentialsParams) error {
	_, err := q.db.Exec(ctx, resetAdminCredentials, arg.ID, arg.PasswordHash)
	return err
}

const setUserLastLogin = `-- name: SetUserLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) SetUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserLastLogin, id)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserConfiguration = `-- name: UpdateUserConfiguration :exec
UPDATE users SET configuration = $1 WHERE id = $2
`

type UpdateUserConfigurationParams struct {
	Configuration json.RawMessage
	ID            uuid.UUID
}

// The user's own settings (library order, hidden libraries, subtitle and
// audio preferences), stored as overrides of Jellyfin's defaults.
func (q *Queries) UpdateUserConfiguration(ctx context.Context, arg UpdateUserConfigurationParams) error {
	_, err := q.db.Exec(ctx, updateUserConfiguration, arg.Configuration, arg.ID)
	return err
}

const updateUserPolicy = `-- name: UpdateUserPolicy :one
UPDATE users SET is_admin = $1, is_disabled = $2, policy = $3
WHERE id = $4
RETURNING id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at
`

type UpdateUserPolicyParams struct {
	IsAdmin    bool
	IsDisabled bool
	Policy     json.RawMessage
	ID         uuid.UUID
}

// An admin's policy change (P4.1): the flags the database owns, and the
// rest of the UserPolicy as stored overrides.
func (q *Queries) UpdateUserPolicy(ctx context.Context, arg UpdateUserPolicyParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPolicy,
		arg.IsAdmin,
		arg.IsDisabled,
		arg.Policy,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.Policy,
		&i.Configuration,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
