// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: userdata.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const markPlayed = `-- name: MarkPlayed :exec

INSERT INTO user_data (user_id, item_id, played, play_count, playback_position_ticks, last_played_at)
SELECT $1, i.id, true, 1, 0, coalesce($2::timestamptz, now())
FROM items i
WHERE i.type IN ('Movie', 'Episode') AND i.missing_since IS NULL
  AND (i.id = $3 OR i.parent_id = $3 OR i.top_parent_id = $3
       OR i.parent_id IN (SELECT s.id FROM items s WHERE s.parent_id = $3))
ON CONFLICT (user_id, item_id) DO UPDATE SET
    played                  = true,
    play_count              = CASE WHEN $2::timestamptz IS NULL THEN greatest(user_data.play_count, 1)
                                   ELSE user_data.play_count + 1 END,
    playback_position_ticks = 0,
    last_played_at          = coalesce($2::timestamptz, user_data.last_played_at, now()),
    updated_at              = now()
`

type MarkPlayedParams struct {
	UserID     uuid.UUID
	DatePlayed *time.Time
	ItemID     uuid.UUID
}

// User data writes (TASKS P1.24, DESIGN §3.11). Played state applies to the
// playable items at or below an item: itself (Movie/Episode), a season's or
// series' episodes, or everything in a library.
// PlayCount becomes at least 1 and only grows when a play date is given;
// the last played date is the given one, else the stored one, else now.
func (q *Queries) MarkPlayed(ctx context.Context, arg MarkPlayedParams) error {
	_, err := q.db.Exec(ctx, markPlayed, arg.UserID, arg.DatePlayed, arg.ItemID)
	return err
}

const markUnplayed = `-- name: MarkUnplayed :exec
UPDATE user_data SET played = false, play_count = 0, playback_position_ticks = 0, last_played_at = NULL, updated_at = now()
WHERE user_id = $1 AND item_id IN (
    SELECT i.id FROM items i
    WHERE i.type IN ('Movie', 'Episode')
      AND (i.id = $2 OR i.parent_id = $2 OR i.top_parent_id = $2
           OR i.parent_id IN (SELECT s.id FROM items s WHERE s.parent_id = $2)))
`

type MarkUnplayedParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

func (q *Queries) MarkUnplayed(ctx context.Context, arg MarkUnplayedParams) error {
	_, err := q.db.Exec(ctx, markUnplayed, arg.UserID, arg.ItemID)
	return err
}

const recordPlayback = `-- name: RecordPlayback :exec
INSERT INTO user_data (user_id, item_id, playback_position_ticks, played, play_count, last_played_at,
                       audio_stream_idx, subtitle_stream_idx)
VALUES ($1, $2, $3, $4, CASE WHEN $4::boolean THEN 1 ELSE 0 END,
        CASE WHEN $5::boolean THEN now() END, $6, $7)
ON CONFLICT (user_id, item_id) DO UPDATE SET
    playback_position_ticks = EXCLUDED.playback_position_ticks,
    played                  = user_data.played OR $4::boolean,
    play_count              = user_data.play_count + CASE WHEN $4::boolean THEN 1 ELSE 0 END,
    last_played_at          = CASE WHEN $5::boolean THEN now() ELSE user_data.last_played_at END,
    audio_stream_idx        = coalesce($6, user_data.audio_stream_idx),
    subtitle_stream_idx     = coalesce($7, user_data.subtitle_stream_idx),
    updated_at              = now()
`

type RecordPlaybackParams struct {
	UserID            uuid.UUID
	ItemID            uuid.UUID
	PositionTicks     int64
	Finished          bool
	Touch             bool
	AudioStreamIdx    *int32
	SubtitleStreamIdx *int32
}

// One playback report (TASKS P2.9, DESIGN §8.4): the resume position,
// whether this play finished the item (played, one more play, position
// reset by the caller), the chosen tracks, and, when touch is set, the
// last played date.
func (q *Queries) RecordPlayback(ctx context.Context, arg RecordPlaybackParams) error {
	_, err := q.db.Exec(ctx, recordPlayback,
		arg.UserID,
		arg.ItemID,
		arg.PositionTicks,
		arg.Finished,
		arg.Touch,
		arg.AudioStreamIdx,
		arg.SubtitleStreamIdx,
	)
	return err
}

const setFavorite = `-- name: SetFavorite :exec
INSERT INTO user_data (user_id, item_id, is_favorite) VALUES ($1, $2, $3)
ON CONFLICT (user_id, item_id) DO UPDATE SET is_favorite = EXCLUDED.is_favorite, updated_at = now()
`

type SetFavoriteParams struct {
	UserID     uuid.UUID
	ItemID     uuid.UUID
	IsFavorite bool
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.Exec(ctx, setFavorite, arg.UserID, arg.ItemID, arg.IsFavorite)
	return err
}

const updateUserData = `-- name: UpdateUserData :exec
INSERT INTO user_data (user_id, item_id, played, play_count, playback_position_ticks, is_favorite, rating, last_played_at)
VALUES ($1, $2, coalesce($3::boolean, false), coalesce($4::int, 0),
        coalesce($5::bigint, 0), coalesce($6::boolean, false),
        $7::real, $8::timestamptz)
ON CONFLICT (user_id, item_id) DO UPDATE SET
    played                  = coalesce($3::boolean, user_data.played),
    play_count              = coalesce($4::int, user_data.play_count),
    playback_position_ticks = coalesce($5::bigint, user_data.playback_position_ticks),
    is_favorite             = coalesce($6::boolean, user_data.is_favorite),
    rating                  = coalesce($7::real, user_data.rating),
    last_played_at          = coalesce($8::timestamptz, user_data.last_played_at),
    updated_at              = now()
`

type UpdateUserDataParams struct {
	UserID        uuid.UUID
	ItemID        uuid.UUID
	Played        *bool
	PlayCount     *int32
	PositionTicks *int64
	IsFavorite    *bool
	Rating        *float32
	LastPlayedAt  *time.Time
}

// NULL arguments keep the stored value.
func (q *Queries) UpdateUserData(ctx context.Context, arg UpdateUserDataParams) error {
	_, err := q.db.Exec(ctx, updateUserData,
		arg.UserID,
		arg.ItemID,
		arg.Played,
		arg.PlayCount,
		arg.PositionTicks,
		arg.IsFavorite,
		arg.Rating,
		arg.LastPlayedAt,
	)
	return err
}
