// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, password_hash, is_admin)
VALUES ($1, $2, $3)
RETURNING id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at
`

type CreateUserParams struct {
	Name         string
	PasswordHash *string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.PasswordHash, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.Policy,
		&i.Configuration,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.Policy,
		&i.Configuration,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at FROM users WHERE name = $1
`

// users.name is citext, so this is case-insensitive like Jellyfin's login.
func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.IsDisabled,
		&i.Policy,
		&i.Configuration,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, password_hash, is_admin, is_disabled, policy, configuration, created_at, last_login_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.IsDisabled,
			&i.Policy,
			&i.Configuration,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAdminCredentials = `-- name: ResetAdminCredentials :exec
UPDATE users SET password_hash = $2, is_admin = true, is_disabled = false WHERE id = $1
`

type ResetAdminCredentialsParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

// Bootstrap/recovery: (re)set the configured admin's password and make sure
// it is an enabled administrator.
func (q *Queries) ResetAdminCredentials(ctx context.Context, arg ResetAdminCredentialsParams) error {
	_, err := q.db.Exec(ctx, resetAdminCredentials, arg.ID, arg.PasswordHash)
	return err
}

const setUserLastLogin = `-- name: SetUserLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) SetUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserLastLogin, id)
	return err
}
