// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: views.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countVisibleChildren = `-- name: CountVisibleChildren :one
SELECT count(*) FROM items WHERE parent_id = $1 AND missing_since IS NULL
`

func (q *Queries) CountVisibleChildren(ctx context.Context, parentID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVisibleChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCollectionFolders = `-- name: ListCollectionFolders :many

SELECT i.id, i.name, i.sort_name, i.date_created, i.date_modified, i.etag,
       l.id AS library_id, l.kind, l.paths
FROM items i JOIN libraries l ON l.id = i.library_id
WHERE i.type = 'CollectionFolder' AND l.enabled
ORDER BY i.sort_name, i.id
`

type ListCollectionFoldersRow struct {
	ID           uuid.UUID
	Name         string
	SortName     string
	DateCreated  time.Time
	DateModified time.Time
	Etag         *string
	LibraryID    uuid.UUID
	Kind         string
	Paths        []string
}

// Library views (TASKS P1.18).
// The top-level folder of every enabled library, in browse order.
func (q *Queries) ListCollectionFolders(ctx context.Context) ([]ListCollectionFoldersRow, error) {
	rows, err := q.db.Query(ctx, listCollectionFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionFoldersRow{}
	for rows.Next() {
		var i ListCollectionFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortName,
			&i.DateCreated,
			&i.DateModified,
			&i.Etag,
			&i.LibraryID,
			&i.Kind,
			&i.Paths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserData = `-- name: ListUserData :many
SELECT user_id, item_id, played, play_count, playback_position_ticks, is_favorite, rating, last_played_at, audio_stream_idx, subtitle_stream_idx, updated_at FROM user_data WHERE user_id = $1 AND item_id = ANY($2::uuid[])
`

type ListUserDataParams struct {
	UserID  uuid.UUID
	ItemIds []uuid.UUID
}

func (q *Queries) ListUserData(ctx context.Context, arg ListUserDataParams) ([]UserDatum, error) {
	rows, err := q.db.Query(ctx, listUserData, arg.UserID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserDatum{}
	for rows.Next() {
		var i UserDatum
		if err := rows.Scan(
			&i.UserID,
			&i.ItemID,
			&i.Played,
			&i.PlayCount,
			&i.PlaybackPositionTicks,
			&i.IsFavorite,
			&i.Rating,
			&i.LastPlayedAt,
			&i.AudioStreamIdx,
			&i.SubtitleStreamIdx,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
