#!/usr/bin/env python3
"""Generate internal/jfapi/dto/{types,mapfields}.gen.go from the pinned Jellyfin openapi.json (TASKS P1.6).

  scripts/gen-dto.py           # regenerate
  scripts/gen-dto.py --check   # exit 1 if types.gen.go is stale

The spec is preprocessed before oapi-codegen runs:
  * format: uuid       -> x-go-type ID    (marshals as 32-hex "N" GUIDs, DESIGN §3.1)
  * format: date-time  -> x-go-type Time  (System.Text.Json style timestamps)
  * BaseItemDto.ChannelId keeps `null` on the wire (x-omitempty: false): Jellyfin
    12.1.0 always sends it, even when null (observed in every captured client).
"""
import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DTO = ROOT / "internal/jfapi/dto"
SPEC = DTO / "openapi.json"
CONFIG = DTO / "oapi-codegen.yaml"
OUT = DTO / "types.gen.go"
MAPS_OUT = DTO / "mapfields.gen.go"

FORMAT_TYPES = {"uuid": "ID", "date-time": "Time"}
# (schema, property) pairs Jellyfin serialises even when null.
ALWAYS_EMIT = [("BaseItemDto", "ChannelId")]
# Dictionary<ImageType, Dictionary<string, string>> is rendered in the spec as
# an inline object with one property per ImageType, which generates an
# unbuildable anonymous struct. Model it as the map it is (same JSON).
ENUM_KEYED_MAPS = [("BaseItemDto", "ImageBlurHashes"), ("BaseItemPerson", "ImageBlurHashes")]


def map_formats(node) -> int:
    """Attach x-go-type to every schema node with a mapped string format."""
    n = 0
    if isinstance(node, dict):
        if node.get("type") == "string" and node.get("format") in FORMAT_TYPES:
            node["x-go-type"] = FORMAT_TYPES[node["format"]]
            n += 1
        for v in node.values():
            n += map_formats(v)
    elif isinstance(node, list):
        for v in node:
            n += map_formats(v)
    return n


def preprocess(spec: dict) -> dict:
    mapped = map_formats(spec)
    schemas = spec["components"]["schemas"]
    for schema, prop in ALWAYS_EMIT:
        schemas[schema]["properties"][prop]["x-omitempty"] = False
    for schema, prop in ENUM_KEYED_MAPS:
        old = schemas[schema]["properties"][prop]
        schemas[schema]["properties"][prop] = {
            "type": "object", "nullable": True, "description": old.get("description", ""),
            "additionalProperties": {"type": "object", "additionalProperties": {"type": "string", "nullable": True}},
        }
    print(f"mapped {mapped} uuid/date-time nodes; {len(schemas)} schemas", file=sys.stderr)
    return spec


def map_depth(node: dict) -> int:
    """How many nested levels of dictionary keys a property's value has."""
    if node.get("type") != "object":
        return 0
    if isinstance(node.get("additionalProperties"), dict):
        return 1 + map_depth(node["additionalProperties"])
    # A C# Dictionary<EnumType, …> is rendered as an inline object whose
    # properties are the enum values (e.g. ImageBlurHashes: {"Primary": {…}}).
    props = node.get("properties") or {}
    if props and "$ref" not in node and all(map_depth(v) for v in props.values()):
        return 1 + max(map_depth(v) for v in props.values())
    return 0


def map_properties(spec: dict) -> str:
    """Go source listing properties whose values are dictionaries. Their keys are
    data, not property names, so the camelCase encoder must leave them alone
    (Jellyfin 12.1.0 keeps e.g. ImageTags {"Primary": …} in both casings)."""
    depths, objects = {}, set()
    for schema in spec["components"]["schemas"].values():
        for name, prop in (schema.get("properties") or {}).items():
            d = map_depth(prop)
            if d:
                depths[name] = max(d, depths.get(name, 0))
            elif "$ref" in prop or "allOf" in prop or prop.get("type") == "object":
                objects.add(name)
    # A name that is a dictionary in one schema and an object in another can't be
    # decided from the key alone; treat it as an object (rename its keys).
    ambiguous = sorted(set(depths) & objects)
    lines = [
        "// Code generated by scripts/gen-dto.py. DO NOT EDIT.",
        "",
        "package dto",
        "",
        "// MapProperties lists JSON properties whose value is a dictionary, with how many",
        "// nested levels of dictionary keys must be kept verbatim when encoding camelCase.",
        f"// Ambiguous names (dictionary in one schema, object in another) are left out: {', '.join(ambiguous) or 'none'}.",
        "var MapProperties = map[string]int{",
    ]
    lines += [f'\t"{n}": {d},' for n, d in sorted(depths.items()) if n not in ambiguous]
    lines += ["}", ""]
    return "\n".join(lines)


def generate(out: Path, maps_out: Path) -> None:
    spec = preprocess(json.loads(SPEC.read_text()))
    with tempfile.TemporaryDirectory() as d:
        tmp = Path(d) / "openapi.json"
        tmp.write_text(json.dumps(spec))
        subprocess.run(["go", "tool", "oapi-codegen", "-config", str(CONFIG), "-o", str(out), str(tmp)],
                       cwd=ROOT, check=True)
    maps_out.write_text(map_properties(spec))
    subprocess.run(["gofmt", "-w", str(maps_out)], check=True)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if not args.check:
        generate(OUT, MAPS_OUT)
        return
    with tempfile.TemporaryDirectory() as d:
        fresh, fresh_maps = Path(d) / OUT.name, Path(d) / MAPS_OUT.name
        generate(fresh, fresh_maps)
        for got, want in ((fresh, OUT), (fresh_maps, MAPS_OUT)):
            if not want.exists() or got.read_bytes() != want.read_bytes():
                sys.exit(f"internal/jfapi/dto/{want.name} is stale: run `make dto`")
        print("generated DTO files are up to date", file=sys.stderr)


if __name__ == "__main__":
    main()
