// Code generated by scripts/gen-dto.py. DO NOT EDIT.

package dto

// MapProperties lists JSON properties whose value is a dictionary, with how many
// nested levels of dictionary keys must be kept verbatim when encoding camelCase.
// Ambiguous names (dictionary in one schema, object in another) are left out: Data.
var MapProperties = map[string]int{
	"Arguments":           1,
	"ArtistProviderIds":   1,
	"CustomPrefs":         1,
	"ImageBlurHashes":     2,
	"ImageTags":           1,
	"ProviderIds":         1,
	"RequiredHttpHeaders": 1,
	"Trickplay":           2,
}
