#!/usr/bin/env python3
"""Endpoint census across all scrubbed captures (TASKS P0.6). Stdlib only.

  scripts/capture/census.py            # writes testdata/jellyfin/CENSUS.md
  scripts/capture/census.py --check    # also exit 1 if a client used an endpoint DESIGN §3.5 lacks

Merges every testdata/jellyfin/<client>/<scenario>/index.json and matches each
endpoint against the paths listed in Plan/DESIGN.md §3.5.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DESIGN = ROOT / "Plan/DESIGN.md"
FIXTURES = ROOT / "testdata/jellyfin"
METHOD_RE = re.compile(r"^([A-Z]+(?:[|/][A-Z]+)*)\s+(/\S*)$")


def design_section(text: str) -> str:
    m = re.search(r"^### 3\.5.*?$(.*?)^##? ", text, re.S | re.M)
    if not m:
        sys.exit("DESIGN.md §3.5 not found")
    return m.group(1)


def expand(path: str) -> list[str]:
    """Expand DESIGN shorthand: `a|b|c` alternatives in the last segment and
    `[optional]` parts. Placeholders like {id} stay as they are."""
    paths = [path]
    while any("[" in p for p in paths):
        nxt = []
        for p in paths:
            m = re.search(r"\[([^\[\]]*)\]", p)
            if m:
                nxt += [p[: m.start()] + p[m.end():], p[: m.start()] + m.group(1) + p[m.end():]]
            else:
                nxt.append(p)
        paths = nxt
    out = []
    for p in paths:
        head, _, last = p.rpartition("/")
        out += [f"{head}/{alt}" for alt in last.split("|")] if "|" in last else [p]
    return out


NON_ID_PLACEHOLDERS = {"playlistid", "segmentid"}  # end in "Id" but aren't GUIDs


def placeholder_regex(path: str) -> str:
    """Captured paths have GUIDs normalised to the literal `{id}`, so ID-like
    placeholders ({id}, {userId}, {msId}, {u}) match only that literal; the rest
    ({type}, {index}, {container}…) match any single segment."""
    out, pos = [], 0
    for m in re.finditer(r"\{([^}]*)\}", path):
        out.append(re.escape(path[pos:m.start()]))
        name = m.group(1).lower()
        id_like = name in ("id", "u") or (name.endswith("id") and name not in NON_ID_PLACEHOLDERS)
        out.append(r"\{id\}" if id_like else r"[^/]+")
        pos = m.end()
    out.append(re.escape(path[pos:]))
    return "".join(out)


def design_routes(text: str) -> list[tuple[set[str] | None, str, re.Pattern]]:
    """(methods or None for any, display path, compiled regex) for every route in §3.5."""
    routes = []
    for raw in re.findall(r"`([^`]+)`", design_section(text)):
        raw = raw.strip()
        m = METHOD_RE.match(raw)
        methods, path = (set(re.split(r"[|/]", m.group(1))), m.group(2)) if m else (None, raw)
        if not path.startswith("/"):
            continue
        path = path.split("?")[0].rstrip("*")
        for p in expand(path):
            routes.append((methods, p, re.compile(f"^{placeholder_regex(p)}$", re.I)))
    return routes


def matches(routes, method: str, path: str) -> str | None:
    for methods, display, rx in routes:
        if rx.match(path) and (methods is None or method in methods):
            return display
    return None


# jellyfin-web's static bundle (hashed .js/.css/fonts) is files, not API: one row is enough.
STATIC_RE = re.compile(r"^(GET|HEAD) /web/(?!ConfigurationPages\b|config\.json$).+", re.I)


def collapse_static(endpoint: str) -> str:
    m = STATIC_RE.match(endpoint)
    return f"{m.group(1)} /web/{{file}}" if m else endpoint


def load_indexes(root: Path) -> list[dict]:
    return [json.loads(p.read_text()) for p in sorted(root.glob("*/*/index.json")) if p.parts[-3] != "_raw"]


def build(root: Path, design_text: str) -> tuple[str, list[str]]:
    indexes = load_indexes(root)
    if not indexes:
        sys.exit(f"no scrubbed index.json under {root}")
    routes = design_routes(design_text)
    clients = [f"{ix['client']}/{ix['scenario']}" for ix in indexes]
    table: dict[str, dict] = {}
    for col, ix in zip(clients, indexes):
        for e in ix["endpoints"]:
            endpoint = collapse_static(e["endpoint"])
            key = endpoint.lower()
            row = table.setdefault(key, {"endpoint": endpoint, "counts": {}, "statuses": {}})
            row["counts"][col] = row["counts"].get(col, 0) + e["count"]
            for st, n in e["statuses"].items():
                row["statuses"][st] = row["statuses"].get(st, 0) + n

    missing, lines = [], []
    lines += ["# Endpoint census", "",
              "Generated by `scripts/capture/census.py` from the scrubbed fixtures. Don't edit by hand.", "",
              f"Clients: {', '.join(clients)}", "",
              "| Endpoint | " + " | ".join(clients) + " | Statuses | DESIGN §3.5 |",
              "|---|" + "---|" * len(clients) + "---|---|"]
    for key in sorted(table, key=lambda k: k.split(" ", 1)[1]):
        row = table[key]
        method, path = row["endpoint"].split(" ", 1)
        hit = matches(routes, method, path)
        if not hit:
            missing.append(row["endpoint"])
        counts = " | ".join(str(row["counts"].get(c, "")) for c in clients)
        statuses = ", ".join(f"{s}×{n}" for s, n in sorted(row["statuses"].items()))
        lines.append(f"| `{row['endpoint']}` | {counts} | {statuses} | {'✓ `' + hit + '`' if hit else '**✗ missing**'} |")

    seen = {matches(routes, r["endpoint"].split(' ', 1)[0], r["endpoint"].split(' ', 1)[1]) for r in table.values()}
    unseen = sorted({d for _, d, _ in routes} - seen)
    lines += ["", f"## Used by clients but not in DESIGN §3.5 ({len(missing)})", ""]
    lines += [f"- `{m}`" for m in missing] or ["- none"]
    lines += ["", f"## In DESIGN §3.5 but not seen in any capture yet ({len(unseen)})", "",
              "Not a problem by itself; these come from other clients or flows that haven't been captured yet.", ""]
    lines += [f"- `{u}`" for u in unseen]
    return "\n".join(lines) + "\n", missing


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--root", type=Path, default=FIXTURES)
    args = ap.parse_args(argv)
    md, missing = build(args.root, DESIGN.read_text())
    out = args.root / "CENSUS.md"
    out.write_text(md)
    print(f"wrote {out.relative_to(ROOT)}; {len(missing)} endpoint(s) missing from DESIGN §3.5")
    for m in missing:
        print("  missing:", m)
    if args.check and missing:
        sys.exit(1)


if __name__ == "__main__":
    main()
